/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yuntong.action;

import java.text.ParseException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.yuntong.action.actionform.G_CarForm;
import com.yuntong.business.vo.G_TruckInfoVO;
import com.yuntong.service.G_ITruckInfoService;


/** 
 * MyEclipse Struts
 * Creation date: 04-08-2007
 * 
 * XDoclet definition:
 * @struts.action path="/g_AddTruckInfo" name="g_CarForm" scope="request" validate="true"
 */
public class G_AddTruckInfoAction extends Action {
	private G_ITruckInfoService truckInfoService;
	/*
	 * Generated Methods
	 */


	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws ParseException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws ParseException {
		G_CarForm car = (G_CarForm) form;// TODO Auto-generated method stub
		
//		String truckBuyDate=car.getTruckBuyDate();
//		int truckStyleID=car.getTruckStyleID();		
//		int truckFixed=car.getTruckFixed();		
//		String truckPhoto=car.getTruckPhoto();
//		String truckInsuranceNum=car.getTruckInsuranceNum();
//		String truckRunNum=car.getTruckRunNum();
//		String truckNum=car.getTruckNum();
//		String truckEngineNum=car.getTruckEngineNum();	
//		int truckCompanyID=car.getTruckCompanyID();	
//		String truckColor=car.getTruckColor();
		String truckBuyDate=request.getParameter("truckBuyDate");
		int truckStyleID=Integer.parseInt(request.getParameter("truckStyleID"));		
		int truckFixed=Integer.parseInt(request.getParameter("truckFixed"));		
		String truckPhoto=request.getParameter("truckPhoto");
		String truckInsuranceNum=request.getParameter("truckInsuranceNum");	
		String truckRunNum=request.getParameter("truckRunNum");	
		String truckNum=request.getParameter("truckNum");	
		String truckEngineNum=request.getParameter("truckEngineNum");	
		int truckCompanyID=Integer.parseInt(request.getParameter("truckCompanyID"));
		String truckColor=request.getParameter("truckColor");
//		Í¼Æ¬Â·¾¶
		String[] str=truckPhoto.replace("\\", "/").split("/");
		String photo=request.getContextPath()+"/picture/car/"+str[str.length-1];
		
		G_TruckInfoVO vo=new G_TruckInfoVO();
		vo.setTruckBuyDate(truckBuyDate);
		vo.setTruckColor(truckColor);
		vo.setTruckCompanyID(truckCompanyID);
		vo.setTruckEngineNum(truckEngineNum);
		vo.setTruckFixed(truckFixed);
		vo.setTruckInsuranceNum(truckInsuranceNum);
		vo.setTruckNum(truckNum);
		vo.setTruckPhoto(photo);
		vo.setTruckRunNum(truckRunNum);
		vo.setTruckStyleID(truckStyleID);
		vo.setIsLeisure(0);
		truckInfoService.addTruckInfo(vo);
		return null;
	}


	public G_ITruckInfoService getTruckInfoService() {
		return truckInfoService;
	}


	public void setTruckInfoService(G_ITruckInfoService truckInfoService) {
		this.truckInfoService = truckInfoService;
	}
}