/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yuntong.action;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.yuntong.business.vo.G_TruckInfoVO;
import com.yuntong.service.G_ITruckInfoService;

/** 
 * MyEclipse Struts
 * Creation date: 04-11-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class G_FindAllTruckAction extends Action {
	private int pageSize;//“≥√Ê¥Û–°
	private G_ITruckInfoService truckInfoService;
	/*
	 * Generated Methods
	 */

	public G_ITruckInfoService getTruckInfoService() {
		return truckInfoService;
	}

	public void setTruckInfoService(G_ITruckInfoService truckInfoService) {
		this.truckInfoService = truckInfoService;
	}

	public int getPageSize() {
		return pageSize;
	}

	public void setPageSize(int pageSize) {
		this.pageSize = pageSize;
	}

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws IOException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		response.setContentType("text/xml; charset=UTF-8");
		PrintWriter out = response.getWriter();
		String page=request.getParameter("curPage");
		int curPage=0;
		if(page.equals("") || page==null || page.equals("0")){
			curPage=1;
		}else{
			curPage=Integer.parseInt(page);
		}
		//int curPage=Integer.parseInt(request.getParameter("curPage"));
		System.out.println("**************************"+curPage);
		List list=truckInfoService.getTruckNumList(pageSize, curPage);
		int totalPage=truckInfoService.getTotalPage(pageSize);
		out.print("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
		out.print("<info>");
		for (int i = 0; i < list.size(); i++) {
			G_TruckInfoVO vo=(G_TruckInfoVO) list.get(i);
			out.print("<truckNumList value='"+vo.getTruckNum()+"'>");
			out.print(vo.getTruckNum());
			out.print("</truckNumList>");
		}
	
		
		out.print("<page>");
		out.print("<totalPage value='"+totalPage+"'>");
		out.print(totalPage);
		out.print("</totalPage>");
		out.print("</page>");
		out.print("</info>");
		out.close();
		return null;
	}
}