/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yuntong.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.yuntong.action.actionform.G_DriverInfoForm;
import com.yuntong.business.vo.G_DriverInfoVO;
import com.yuntong.service.G_IDriverInfoService;
import com.yuntong.service.G_IFilialeService;

/** 
 * MyEclipse Struts
 * Creation date: 04-08-2007
 * 
 * XDoclet definition:
 * @struts.action path="/g_GoDriverInfo" name="g_DriverInfoForm" scope="request" validate="true"
 */
public class G_GoDriverInfoAction extends Action {
	private G_IFilialeService filialeService;
	

	public G_IFilialeService getFilialeService() {
		return filialeService;
	}


	public void setFilialeService(G_IFilialeService filialeService) {
		this.filialeService = filialeService;
	}


	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		List filialeList=filialeService.getFilialeNameAndID();
		request.getSession().setAttribute("filialeList", filialeList);
		return mapping.findForward("addDriver");
	}
}