/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yuntong.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.yuntong.business.vo.G_TruckInfoAndStyleVO;

/** 
 * MyEclipse Struts
 * Creation date: 04-11-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="snps2" path="/PSGL/G_snps2.jsp" redirect="true"
 */
public class G_GoSNPS2Action extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String driverName=request.getParameter("hdName");
		String truckNum=request.getParameter("htNum");
		int truckId=Integer.parseInt(request.getParameter("htId"));
		int driverId=Integer.parseInt(request.getParameter("hdId"));
		long bulk=Long.parseLong(request.getParameter("hbulk"));
		long heft=Long.parseLong(request.getParameter("hheft"));
		G_TruckInfoAndStyleVO vo=new G_TruckInfoAndStyleVO();
		vo.setDriverId(driverId);
		vo.setDriverName(driverName);
		vo.setTruckId(truckId);
		vo.setTruckNum(truckNum);
		vo.setTruckStyleCubage(bulk);
		vo.setTruckStyleTonnage(heft);
		HttpSession session=request.getSession();
		session.setAttribute("info",vo);
		return mapping.findForward("scps2");
	}
}