/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yuntong.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.yuntong.service.G_IAreaInfoService;
import com.yuntong.service.G_IDriverInfoService;
import com.yuntong.service.G_ITruckInfoService;
import com.yuntong.service.Y_IAreaManagerService;
import com.yuntong.service.impl.Y_AreaInfoManager;

/** 
 * MyEclipse Struts
 * Creation date: 04-09-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="sjys" path="/G_sjys1.jsp"
 */
public class G_GoSJYSAction extends Action {
	private G_ITruckInfoService truckInfoService;
	private G_IDriverInfoService driverInfoService;
	private Y_IAreaManagerService areaManagerService;
	/*
	 * Generated Methods
	 */



	public Y_IAreaManagerService getAreaManagerService() {
		return areaManagerService;
	}

	public void setAreaManagerService(Y_IAreaManagerService areaManagerService) {
		this.areaManagerService = areaManagerService;
	}

	public G_IDriverInfoService getDriverInfoService() {
		return driverInfoService;
	}

	public void setDriverInfoService(G_IDriverInfoService driverInfoService) {
		this.driverInfoService = driverInfoService;
	}

	public G_ITruckInfoService getTruckInfoService() {
		return truckInfoService;
	}

	public void setTruckInfoService(G_ITruckInfoService truckInfoService) {
		this.truckInfoService = truckInfoService;
	}

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		List driverInfoList=driverInfoService.getDrinerIsLeisure(0);
		List truckInfoList=truckInfoService.getTruckIsLeisure(0);
		List areaInfoList=areaManagerService.findAllAreaInfo();
		HttpSession session=request.getSession();
		session.setAttribute("driverInfoList", driverInfoList);
		session.setAttribute("truckInfoList",truckInfoList);
		session.setAttribute("areaInfoList",areaInfoList);
		return mapping.findForward("sjys");
	}
}