/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yuntong.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.yuntong.business.vo.G_FilialeInfoVO;
import com.yuntong.business.vo.G_TruckInfoVO;
import com.yuntong.business.vo.G_TruckStyleVO;
import com.yuntong.service.G_IFilialeService;
import com.yuntong.service.G_ITruckStyleService;

/** 
 * MyEclipse Struts
 * Creation date: 04-08-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="psgl" path="/PSGL/G_addCar.jsp"
 */
public class G_GoPSGLAction extends Action {
	private G_IFilialeService filialeService;
	private G_ITruckStyleService truckStyleService;
	/*
	 * Generated Methods
	 */

	public G_IFilialeService getFilialeService() {
		return filialeService;
	}

	public void setFilialeService(G_IFilialeService filialeService) {
		this.filialeService = filialeService;
	}

	public G_ITruckStyleService getTruckStyleService() {
		return truckStyleService;
	}

	public void setTruckStyleService(G_ITruckStyleService truckStyleService) {
		this.truckStyleService = truckStyleService;
	}

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		List filialeList=filialeService.getFilialeNameAndID();
		List truckStyleList=truckStyleService.getAllTruckStyle();
		HttpSession session=request.getSession();
		session.setAttribute("filialeList",filialeList);
		session.setAttribute("truckStyleList", truckStyleList);
		return mapping.findForward("psgl");
	}
}