/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yuntong.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.yuntong.business.vo.CheckRigVO;
import com.yuntong.service.J_FareMathService;

/** 
 * MyEclipse Struts
 * Creation date: 04-12-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class J_CheckRigActionAction extends Action {
	private J_FareMathService fareMathServices; 
	/*
	 * Generated Methods
	 */

	public J_FareMathService getFareMathServices() {
		return fareMathServices;
	}

	public void setFareMathServices(J_FareMathService fareMathServices) {
		this.fareMathServices = fareMathServices;
	}

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		CheckRigVO vo= (CheckRigVO) request.getSession().getAttribute("check");
		int rid=vo.getRegisterId();
		int typeid=vo.getRstateID();
		fareMathServices.RigStateChange(rid, typeid);
		return mapping.findForward("indexs");
	}
}