/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yuntong.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.yuntong.service.M_TAgionInfoManagerService;

/** 
 * MyEclipse Struts
 * Creation date: 04-05-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class M_selectAction extends Action {
	private M_TAgionInfoManagerService M_service;
	/*
	 * Generated Methods
	 */

	public M_TAgionInfoManagerService getM_service() {
		return M_service;
	}

	public void setM_service(M_TAgionInfoManagerService m_service) {
		M_service = m_service;
	}

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String type=request.getParameter("NameOrId").trim();
		String value=request.getParameter("leixin").trim();
		List list=M_service.selectInfo(type, value);
		request.getSession().setAttribute("agionInfoList", list);
		// TODO Auto-generated method stub
		return mapping.findForward("select");
	}
}