/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yuntong.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.yuntong.hibernate.database.po.TAgioInfo;
import com.yuntong.hibernate.database.po.TAgioType;
import com.yuntong.hibernate.database.po.TRegisterInfo;
import com.yuntong.service.M_TAgionInfoManagerService;

/** 
 * MyEclipse Struts
 * Creation date: 04-09-2007
 * 
 * XDoclet definition:
 * @struts.action
 * @struts.action-forward name="updateok" path="/M_scgl_1.jsp"
 */
public class UpdateInfoAction extends Action {
	private M_TAgionInfoManagerService M_service;
	/*
	 * Generated Methods
	 */

	public M_TAgionInfoManagerService getM_service() {
		return M_service;
	}

	public void setM_service(M_TAgionInfoManagerService m_service) {
		M_service = m_service;
	}

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
	try {
		TAgioInfo info= new TAgioInfo();
		
		int id =Integer.parseInt(request.getParameter("agioId"));
		System.out.println("id-----------"+id);
		int piaoid=Integer.parseInt(request.getParameter("registerId").trim());
		int leiid=Integer.parseInt(request.getParameter("atypeId").trim());
		float money=Float.parseFloat(request.getParameter("agioMoney").trim());
		String beizhu=request.getParameter("agioInfo");
		
		//±àºÅ
		info.setAgioId(id);
		//ÀàÐÍ±àºÅ
		TAgioType type= new TAgioType();
		type.setAtypeId(leiid);
		info.setTAgioType(type);
		//Æ±±àºÅ
		TRegisterInfo tr= new TRegisterInfo();
		tr.setRegisterId(piaoid);
		info.setTRegisterInfo(tr);
		//Ç®
		info.setAgioMoney(money);
		//±¸×¢
		info.setAgioInfo(beizhu);
		//Ö´ÐÐ¸üÐÂ
		M_service.updateInfo(info);
		List list=M_service.getAllInfo();
		request.getSession().setAttribute("agionInfoList",list);
	} catch (Exception e) {
		e.printStackTrace();
	}
		return mapping.findForward("updateok");
	}
}