/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yuntong.action;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.yuntong.hibernate.database.po.TClientInfo;
import com.yuntong.hibernate.database.po.TFactoryInfo;
import com.yuntong.service.Y_IClientManagerService;

/** 
 * MyEclipse Struts
 * Creation date: 04-26-2007
 * 客户信息的google查询
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class Y_findcinfoAction extends Action {
	private Y_IClientManagerService clientManagerService;
	public Y_IClientManagerService getClientManagerService() {
		return clientManagerService;
	}
	public void setClientManagerService(Y_IClientManagerService clientManagerService) {
		this.clientManagerService = clientManagerService;
	}
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		PrintWriter out= response.getWriter();
	     String typing = request.getParameter("typing");
	     int cid;
	     try{
	      cid=Integer.parseInt(typing);
	     }catch(Exception e){
	    	 return null;
	     }
		 // .........
	     List list=null;
	    try {
	    	 list=clientManagerService.findTopTen(cid);
		} catch (Exception e) {
			return null;
		}
		if(list==null){
			return null;
		}
	    
	    int temp=list.size();
	    if(list.size()>=10){
	    	temp=10;
	    }else{
	    	temp=list.size();
	    }
	    for (int i = 0; i < temp; i++) {
	    	
	    	out.println("<div onselect='this.text.value = "+((TClientInfo)(list.get(i))).getClientId()+"'><span class=''>"+((TClientInfo)(list.get(i))).getClientId()+"</span></div>");	    
	    	        
	    }  
		return null;
		
	}
}