/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yuntong.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.yuntong.service.Y_IAreaManagerService;

/** 
 * MyEclipse Struts
 * Creation date: 03-26-2007
 * 从主页面跳转到收货管理
 * 初试化地区信息
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="shdj" path="/Y_shgl_1.jsp"
 */
public class Y_GoSHGLAction extends Action {
	private Y_IAreaManagerService service;
	/*
	 * Generated Methods
	 */

	public Y_IAreaManagerService getService() {
		return service;
	}

	public void setService(Y_IAreaManagerService service) {
		this.service = service;
	}

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		//得到地区信息并保存到session中
		List list=service.findAllAreaInfo();
		HttpSession session=request.getSession();
		session.setAttribute("cityinfo", list);
		return mapping.findForward("shdj");
	}
}