/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yuntong.action;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.yuntong.hibernate.database.po.TFactoryInfo;
import com.yuntong.service.Y_IFactoryManagerService;

/** 
 * MyEclipse Struts
 * Creation date: 04-26-2007
 * ÊÕ»õµÇ¼Çgoogle
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class Y_selectFinfoAction extends Action {
	private Y_IFactoryManagerService factoryManagerService;
	public Y_IFactoryManagerService getFactoryManagerService() {
		return factoryManagerService;
	}
	public void setFactoryManagerService(
			Y_IFactoryManagerService factoryManagerService) {
		this.factoryManagerService = factoryManagerService;
	}
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		PrintWriter out= response.getWriter();
	     String typing = request.getParameter("typing");
	     int fid;
	     try{
	      fid=Integer.parseInt(typing);
	     }catch(Exception e){
	    	 return null;
	     }
		 // .........
	     List list=null;
	    try {
	    	 list=factoryManagerService.findTopTen(fid);
		} catch (Exception e) {
			return null;
		}
		if(list==null){
			return null;
		}
	    
	    int temp=list.size();
	    if(list.size()>=10){
	    	temp=10;
	    }else{
	    	temp=list.size();
	    }
	    for (int i = 0; i < temp; i++) {
	    	
	    	out.println("<div onselect='this.text.value = "+((TFactoryInfo)(list.get(i))).getFactoryId()+"'><span class=''>"+((TFactoryInfo)(list.get(i))).getFactoryId()+"</span></div>");
	    
	    	        
	    }  
		return null;
	}
}