/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yuntong.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-09-2007
 * 
 * XDoclet definition:
 * @struts.form name="x_loseForm"
 */
public class X_loseForm extends ValidatorForm {
	/*
	 * Generated fields
	 */

	/** rowId property */
//	private int rowId;

	/** regId property */
	private Long regId;
//	private String goodName;

	/*
	 * Generated Methods
	 */

//	public String getGoodName() {
//		return goodName;
//	}
//
//	public void setGoodName(String goodName) {
//		this.goodName = goodName;
//	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the rowId.
	 * @return String
	 */
//	public int getRowId() {
//		return rowId;
//	}
//
//	/** 
//	 * Set the rowId.
//	 * @param rowId The rowId to set
//	 */
//	public void setRowId(int rowId) {
//		this.rowId = rowId;
//	}

	/** 
	 * Returns the regId.
	 * @return String
	 */
	public Long getRegId() {
		return regId;
	}

	/** 
	 * Set the regId.
	 * @param regId The regId to set
	 */
	public void setRegId(Long regId) {
		this.regId = regId;
	}
}