/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yuntong.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-03-2007
 * 
 * XDoclet definition:
 * @struts.form name="x_perForm"
 */
public class X_perForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** perID property */
	private Long perID;
	private String perName;

	/*
	 * Generated Methods
	 */

	public String getPerName() {
		return perName;
	}

	public void setPerName(String perName) {
		this.perName = perName;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the perID.
	 * @return Integer
	 */
	public Long getPerID() {
		return perID;
	}

	/** 
	 * Set the perID.
	 * @param perID The perID to set
	 */
	public void setPerID(Long perID) {
		this.perID = perID;
	}
}