/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yuntong.action.ajaxaction;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.Date;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.yuntong.business.vo.CheckRigVO;
import com.yuntong.business.vo.J_FareMathVo;
import com.yuntong.business.vo.StateVO;
import com.yuntong.business.vo.Y_MarketInfoVO;
import com.yuntong.service.J_FareMathService;

/** 
 * MyEclipse Struts
 * Creation date: 04-11-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class CheckRigAjaxActionAction extends Action {
	private  	J_FareMathService fareMathService; 
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws IOException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		response.setContentType("text/xml; charset=UTF-8");
		
         PrintWriter out = response.getWriter();
      
         //J_FareMathVo vo=(J_FareMathVo) request.getSession().getAttribute("vo");
       int id=Integer.parseInt(request.getParameter("id"));
          //  int id= vo.getRegisterId();
       System.out.println("sssssssssssssss"+id);
       CheckRigVO fareMathVos=fareMathService.CheckRig(id);
	request.getSession().setAttribute("check",fareMathVos);
	int RegisterID=fareMathVos.getRegisterId();
    Long RegisterGlideID=fareMathVos.getRegisterGlideId();
    int RegisterGoodsID=fareMathVos.getRegisterGoodsID();
   int	RegisterFactoryID=fareMathVos.getRegisterFactoryID();
   Long RegisterClientID=fareMathVos.getRegisterClientID();
   String  RegisterConveyanceID=fareMathVos.getRegisterConveyanceId();              
	String   RegisterLine=fareMathVos.getRegisterLine();
	int RegisterFreightID=fareMathVos.getTFreightStyleID();
	String RegisterPayerName=fareMathVos.getRegisterPayerName();
	int RegisterUserID=fareMathVos.getRegisterUserID();
	 Date  RegisterDate   =  fareMathVos.getRegisterDate();
	int RegisterState=fareMathVos.getRstateID();
	System.out.println("state is"+RegisterState);
	 String RegisterRemark=fareMathVos.getRegisterRemark();
        
	

		
			
		
		
	
//		拼写并打印xml文件RegisterRemark
		
		out.println("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
		out.println("<info>");
		
		
		   out.println("<RegisterID>");
		    out.println(RegisterID+"");
			out.println("</RegisterID>");
			
			out.println("<RegisterGlideID>");
				out.println(RegisterGlideID+"");
			out.println("</RegisterGlideID>");
			
			out.println("<RegisterGoodsID>");
				out.println(RegisterGoodsID+"");
			out.println("</RegisterGoodsID>");

			out.println("<RegisterFactoryID>");
				out.println(RegisterFactoryID+"");
			out.println("</RegisterFactoryID>");

			out.println("<RegisterClientID>");
				out.println(RegisterClientID+"");
			out.println("</RegisterClientID>");

			out.println("<RegisterConveyanceID>");
				out.println(RegisterConveyanceID+"");
			out.println("</RegisterConveyanceID>");
			out.println("<RegisterLine>");
			out.println(RegisterLine+"");
		    out.println("</RegisterLine>");

			out.println("<RegisterFreightID>");
				out.println(RegisterFreightID+"");
			out.println("</RegisterFreightID>");
	
			out.println("<RegisterPayerName>");
				out.println(RegisterPayerName+"");
			out.println("</RegisterPayerName>");

			out.println("<RegisterUserID>");
				out.println(RegisterUserID+"");
			out.println("</RegisterUserID>");

			out.println("<RegisterDate>");
				out.println(RegisterDate+"");
			out.println("</RegisterDate>");
			
			out.println("<RegisterState>");
			out.println(RegisterState+"");
		    out.println("</RegisterState>");
		    out.println("<RegisterRemark>");
			out.println(RegisterRemark+"");
		    out.println("</RegisterRemark>");
		   
			
		out.println("</info>");
	
	     out.close();
				return null;
	
	}

	public J_FareMathService getFareMathService() {
		return fareMathService;
	}

	public void setFareMathService(J_FareMathService fareMathService) {
		this.fareMathService = fareMathService;
	}
}