/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yuntong.action.ajaxaction;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.yuntong.hibernate.database.po.TRegisterInfo;
import com.yuntong.hibernate.database.po.TTruckInfo;
import com.yuntong.service.G_ITruckInfoService;

/** 
 * MyEclipse Struts
 * Creation date: 04-27-2007
 * 添加车辆google效果
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class G_googleTruckAction extends Action {
		private G_ITruckInfoService infoService;
		public G_ITruckInfoService getInfoService() {
			return infoService;
		}
		public void setInfoService(G_ITruckInfoService infoService) {
			this.infoService = infoService;
		}
		public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
			PrintWriter out= response.getWriter();
			String id=request.getParameter("typing");
		
			 List list=null;
			    try {
			    	 list=infoService.findTopTen(id);
			    	 
				} catch (Exception e) {
					return null;
				}
				if(list==null){
					return null;
				}
			    
			    int temp=list.size();
			    if(list.size()>=10){
			    	temp=10;
			    }else{
			    	temp=list.size();
			    }
			    for (int i = 0; i < temp; i++) {		    	
			    	out.println("<div onselect='this.text.value = "+((TTruckInfo)(list.get(i))).getTruckNum()+"'><span class=''>"+((TTruckInfo)(list.get(i))).getTruckNum()+"</span></div>");		    		    	        
			    }  
			return null;
	}
}