/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yuntong.action.ajaxaction;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.Date;


import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.yuntong.business.vo.J_FareMathVo;
import com.yuntong.service.J_FareMathService;


/** 
 * MyEclipse Struts
 * Creation date: 03-30-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class J_FareMathAjaxActionAction extends Action {
 private  	J_FareMathService fareMathService; 
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws IOException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)  {
		// TODO Auto-generated method stub
		
		response.setContentType("text/xml; charset=UTF-8");
		try {
	   PrintWriter out = response.getWriter();
	
	
		int id=Integer.parseInt(request.getParameter("id"));
		System.out.println("======================================"+id);
		try{
			if (fareMathService==null) {
				System.out.println("fareMathService is nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn");
			}
		J_FareMathVo fareMathVo=fareMathService.FindregisterId(id);
		 request.getSession().setAttribute("vo",fareMathVo);
		int RegisterID=fareMathVo.getRegisterId();
	    Long RegisterGlideID=fareMathVo.getRegisterGlideId();
        int RegisterGoodsID=fareMathVo.getRegisterGoodsID();
        int	RegisterFactoryID=fareMathVo.getRegisterFactoryID();
        Long RegisterClientID=fareMathVo.getRegisterClientID();
	    String  RegisterConveyanceID=fareMathVo.getRegisterConveyanceId();              
		String   RegisterLine=fareMathVo.getRegisterLine();
		int RegisterFreightID=fareMathVo.getTFreightStyleID();
		String RegisterPayerName=fareMathVo.getRegisterPayerName();
		int RegisterUserID=fareMathVo.getRegisterUserID();
		 Date  RegisterDate   =  fareMathVo.getRegisterDate();
		String RegisterState=fareMathVo.getRstateName();
	
		 String RegisterRemark=fareMathVo.getRegisterRemark();
//		拼写并打印xml文件RegisterRemark
		
		out.println("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
		out.println("<info>");
		
		
		   out.println("<RegisterID>");
		    out.println(RegisterID+"");
			out.println("</RegisterID>");
			
			out.println("<RegisterGlideID>");
				out.println(RegisterGlideID+"");
			out.println("</RegisterGlideID>");
			
			out.println("<RegisterGoodsID>");
				out.println(RegisterGoodsID+"");
			out.println("</RegisterGoodsID>");

			out.println("<RegisterFactoryID>");
				out.println(RegisterFactoryID+"");
			out.println("</RegisterFactoryID>");

			out.println("<RegisterClientID>");
				out.println(RegisterClientID+"");
			out.println("</RegisterClientID>");

			out.println("<RegisterConveyanceID>");
				out.println(RegisterConveyanceID+"");
			out.println("</RegisterConveyanceID>");
			out.println("<RegisterLine>");
			out.println(RegisterLine+"");
		    out.println("</RegisterLine>");

			out.println("<RegisterFreightID>");
				out.println(RegisterFreightID+"");
			out.println("</RegisterFreightID>");
	
			out.println("<RegisterPayerName>");
				out.println(RegisterPayerName+"");
			out.println("</RegisterPayerName>");

			out.println("<RegisterUserID>");
				out.println(RegisterUserID+"");
			out.println("</RegisterUserID>");

			out.println("<RegisterDate>");
				out.println(RegisterDate+"");
			out.println("</RegisterDate>");
			out.println("<RegisterState>");
			out.println(RegisterState+"");
		    out.println("</RegisterState>");
		    out.println("<RegisterRemark>");
			out.println(RegisterRemark+"");
		    out.println("</RegisterRemark>");
		   
			
		out.println("</info>");
		out.close();
		}catch(Exception e){
			
			e.printStackTrace();
		}
	} catch (IOException e) {
		
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
	
          
		return null;
		
	}

	public J_FareMathService getFareMathService() {
		return fareMathService;
	}

	public void setFareMathService(J_FareMathService fareMathService) {
		this.fareMathService = fareMathService;
	}

	
}