/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yuntong.action.ajaxaction;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.yuntong.hibernate.database.dao.TRegisterInfoDAO;
import com.yuntong.hibernate.database.po.TRegisterInfo;
import com.yuntong.service.J_FareMathService;

/** 
 * MyEclipse Struts
 * Creation date: 04-27-2007
 * ·ÑÓÃ¹ÀËãgoogle
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class J_googleFYGSAction extends Action {
	private J_FareMathService fareMathService;
	public J_FareMathService getFareMathService() {
		return fareMathService;
	}
	public void setFareMathService(J_FareMathService fareMathService) {
		this.fareMathService = fareMathService;
	}
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		PrintWriter out= response.getWriter();
		String id=request.getParameter("typing");
		
		 List list=null;
		    try {
		    	TRegisterInfoDAO dao=new TRegisterInfoDAO();
		    	 list=fareMathService.findTopTen(Integer.parseInt(id));
		    	 
			} catch (Exception e) {
				return null;
			}
			if(list==null){
				return null;
			}
		    
		    int temp=list.size();
		    if(list.size()>=10){
		    	temp=10;
		    }else{
		    	temp=list.size();
		    }
		    for (int i = 0; i < temp; i++) {		    	
		    	out.println("<div onselect='this.text.value = "+((TRegisterInfo)(list.get(i))).getRegisterId()+"'><span class=''>"+((TRegisterInfo)(list.get(i))).getRegisterId()+"</span></div>");		    		    	        
		    }  
		return null;
	}
}