/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yuntong.action.ajaxaction;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.yuntong.business.vo.J_ShaoVO;
import com.yuntong.service.J_ShaoShouKuanService;

/** 
 * MyEclipse Struts
 * Creation date: 04-08-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class J_ShaoShouKuanAjaxAction extends Action {
	/*
	 * Generated Methods
	 */
private J_ShaoShouKuanService kuanService;
	
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		response.setContentType("text/xml; charset=UTF-8");
		
		try{
			  PrintWriter out = response.getWriter();

			  int id=Integer.parseInt(request.getParameter("id"));
	            System.out.println(id);
			  J_ShaoVO shaoVO=kuanService.ShaoShouKuan(id);
			  if(shaoVO==null){
				  
				  
				  System.out.println("sssssssssssssssssssssssss");
			  }
		int agioid=shaoVO.getAgioId();
		
		int agiotype=shaoVO.getTAgioType();
		
		int agioRid=shaoVO.getTRegisterID();
		
		float agiomoney=shaoVO.getAgioMoney();
		
		
		String agioinfo=shaoVO.getAgioInfo();
		
//		拼写并打印xml文件RegisterRemark
		
		
	
		out.println("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
		out.println("<info>");
	          out.println("<agioid>");
		    out.println(agioid+"");
			out.println("</agioid>");
			
			out.println("<agiotype>");
				out.println(agiotype+"");
			out.println("</agiotype>");
			
			out.println("<agioRid>");
				out.println(agioRid+"");
			out.println("</agioRid>");

			out.println("<agiomoney>");
				out.println(agiomoney+"");
			out.println("</agiomoney>");

			out.println("<agioinfo>");
				out.println(agioinfo+"");
			out.println("</agioinfo>");
           out.println("</info>");
           out.close();
		} catch (IOException e) {
			
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return null;
		
	}
	public J_ShaoShouKuanService getKuanService() {
		return kuanService;
	}
	public void setKuanService(J_ShaoShouKuanService kuanService) {
		this.kuanService = kuanService;
	}
}