/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yuntong.action.ajaxaction;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.yuntong.service.Y_IAreaFreightInfoService;


/** 
 * MyEclipse Struts
 * Creation date: 04-23-2007
 * 删除运时运费信息
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class Y_deleteYSYFAction extends Action {
	private Y_IAreaFreightInfoService areaFreightInfoService;
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//得到编号
		String strId=request.getParameter("delid");
		int id=Integer.parseInt(strId);
		//删除信息
		areaFreightInfoService.deleteInfoById(id);		
		return null;
	}
	
	public Y_IAreaFreightInfoService getAreaFreightInfoService() {
		return areaFreightInfoService;
	}
	public void setAreaFreightInfoService(
			Y_IAreaFreightInfoService areaFreightInfoService) {
		this.areaFreightInfoService = areaFreightInfoService;
	}
}