/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yuntong.action.ajaxaction;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.yuntong.hibernate.database.po.TRegisterInfo;
import com.yuntong.service.Y_IRegisterManagerService;

/** 
 * MyEclipse Struts
 * Creation date: 04-27-2007
 * 损货登记google效果
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class Y_googleSHDJAction extends Action {
	private Y_IRegisterManagerService registerManagerService;
		public Y_IRegisterManagerService getRegisterManagerService() {
		return registerManagerService;
	}
	public void setRegisterManagerService(
			Y_IRegisterManagerService registerManagerService) {
		this.registerManagerService = registerManagerService;
	}
		public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)  throws IOException{
			PrintWriter out= response.getWriter();
			String id=request.getParameter("typing");
		System.out.println("fffffffffffffff"+id);
			 List list=null;
			    try {
			    	 list=registerManagerService.findTopTen(id);
			    	 
				} catch (Exception e) {
					return null;
				}
				if(list==null){
					return null;
				}
			    
			    int temp=list.size();
			    if(list.size()>=10){
			    	temp=10;
			    }else{
			    	temp=list.size();
			    }
			    for (int i = 0; i < temp; i++) {		    	
			    	out.println("<div onselect='this.text.value = "+((TRegisterInfo)(list.get(i))).getRegisterGlideId()+"'><span class=''>"+((TRegisterInfo)(list.get(i))).getRegisterGlideId()+"</span></div>");		    		    	        
			    }  
			return null;
	}
}