/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yuntong.action.actionform;

import java.util.Date;
import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-07-2007
 * 
 * XDoclet definition:
 * @struts.form name="g_CarForm"
 */
public class G_CarForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** truckBuyDate property */
	private String truckBuyDate;

	/** truckStyleID property */
	private int truckStyleID;

	/** truckFixed property */
	private int truckFixed;

	/** truckPhoto property */
	private String truckPhoto;

	/** truckInsuranceNum property */
	private String truckInsuranceNum;

	/** truckRunNum property */
	private String truckRunNum;

	/** truckNum property */
	private String truckNum;

	/** truckEngineNum property */
	private String truckEngineNum;

	/** truckCompanyID property */
	private int truckCompanyID;

	/** truckColor property */
	private String truckColor;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the truckBuyDate.
	 * @return Date
	 */
	
	/** 
	 * Returns the truckStyleID.
	 * @return int
	 */
	public int getTruckStyleID() {
		return truckStyleID;
	}

	/** 
	 * Set the truckStyleID.
	 * @param truckStyleID The truckStyleID to set
	 */
	public void setTruckStyleID(int truckStyleID) {
		this.truckStyleID = truckStyleID;
	}

	/** 
	 * Returns the truckFixed.
	 * @return int
	 */
	public int getTruckFixed() {
		return truckFixed;
	}

	/** 
	 * Set the truckFixed.
	 * @param truckFixed The truckFixed to set
	 */
	public void setTruckFixed(int truckFixed) {
		this.truckFixed = truckFixed;
	}

	/** 
	 * Returns the truckPhoto.
	 * @return String
	 */
	public String getTruckPhoto() {
		return truckPhoto;
	}

	/** 
	 * Set the truckPhoto.
	 * @param truckPhoto The truckPhoto to set
	 */
	public void setTruckPhoto(String truckPhoto) {
		this.truckPhoto = truckPhoto;
	}

	/** 
	 * Returns the truckInsuranceNum.
	 * @return String
	 */
	public String getTruckInsuranceNum() {
		return truckInsuranceNum;
	}

	/** 
	 * Set the truckInsuranceNum.
	 * @param truckInsuranceNum The truckInsuranceNum to set
	 */
	public void setTruckInsuranceNum(String truckInsuranceNum) {
		this.truckInsuranceNum = truckInsuranceNum;
	}

	/** 
	 * Returns the truckRunNum.
	 * @return String
	 */
	public String getTruckRunNum() {
		return truckRunNum;
	}

	/** 
	 * Set the truckRunNum.
	 * @param truckRunNum The truckRunNum to set
	 */
	public void setTruckRunNum(String truckRunNum) {
		this.truckRunNum = truckRunNum;
	}

	/** 
	 * Returns the truckNum.
	 * @return String
	 */
	public String getTruckNum() {
		return truckNum;
	}

	/** 
	 * Set the truckNum.
	 * @param truckNum The truckNum to set
	 */
	public void setTruckNum(String truckNum) {
		this.truckNum = truckNum;
	}

	/** 
	 * Returns the truckEngineNum.
	 * @return String
	 */
	public String getTruckEngineNum() {
		return truckEngineNum;
	}

	/** 
	 * Set the truckEngineNum.
	 * @param truckEngineNum The truckEngineNum to set
	 */
	public void setTruckEngineNum(String truckEngineNum) {
		this.truckEngineNum = truckEngineNum;
	}

	/** 
	 * Returns the truckCompanyID.
	 * @return int
	 */
	public int getTruckCompanyID() {
		return truckCompanyID;
	}

	/** 
	 * Set the truckCompanyID.
	 * @param truckCompanyID The truckCompanyID to set
	 */
	public void setTruckCompanyID(int truckCompanyID) {
		this.truckCompanyID = truckCompanyID;
	}

	/** 
	 * Returns the truckColor.
	 * @return String
	 */
	public String getTruckColor() {
		return truckColor;
	}

	/** 
	 * Set the truckColor.
	 * @param truckColor The truckColor to set
	 */
	public void setTruckColor(String truckColor) {
		this.truckColor = truckColor;
	}

	public String getTruckBuyDate() {
		return truckBuyDate;
	}

	public void setTruckBuyDate(String truckBuyDate) {
		this.truckBuyDate = truckBuyDate;
	}


}