/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yuntong.action.actionform;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.yuntong.hibernate.database.po.TAgioType;
import com.yuntong.hibernate.database.po.TRegisterInfo;

/** 
 * MyEclipse Struts
 * Creation date: 04-09-2007
 * 
 * XDoclet definition:
 * @struts.form name="j_ShaoShouKuanForm"
 */
public class J_ShaoShouKuanForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** agioGoodsID property */
	private int agioGoodsID;

	/** agioTypeID property */
	private int agioTypeID;

	/** agioInfo property */
	private String agioInfo;

	/** agioMoney property */
	private float agioMoney;

	/** agioID property */
	private int agioID;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the agioGoodsID.
	 * @return int
	 */
	public int getAgioGoodsID() {
		return agioGoodsID;
	}

	/** 
	 * Set the agioGoodsID.
	 * @param agioGoodsID The agioGoodsID to set
	 */
	public void setAgioGoodsID(int agioGoodsID) {
		this.agioGoodsID = agioGoodsID;
	}

	/** 
	 * Returns the agioTypeID.
	 * @return String
	 */
	public int getAgioTypeID() {
		return agioTypeID;
	}

	/** 
	 * Set the agioTypeID.
	 * @param agioTypeID The agioTypeID to set
	 */
	public void setAgioTypeID(int agioTypeID) {
		this.agioTypeID = agioTypeID;
	}

	/** 
	 * Returns the agioInfo.
	 * @return String
	 */
	public String getAgioInfo() {
		return agioInfo;
	}

	/** 
	 * Set the agioInfo.
	 * @param agioInfo The agioInfo to set
	 */
	public void setAgioInfo(String agioInfo) {
		this.agioInfo = agioInfo;
	}

	/** 
	 * Returns the agioMoney.
	 * @return float
	 */
	public float getAgioMoney() {
		return agioMoney;
	}

	/** 
	 * Set the agioMoney.
	 * @param agioMoney The agioMoney to set
	 */
	public void setAgioMoney(float agioMoney) {
		this.agioMoney = agioMoney;
	}

	/** 
	 * Returns the agioID.
	 * @return int
	 */
	public int getAgioID() {
		return agioID;
	}

	/** 
	 * Set the agioID.
	 * @param agioID The agioID to set
	 */
	public void setAgioID(int agioID) {
		this.agioID = agioID;
	}
}