/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yuntong.action.actionform;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-23-2007
 * 
 * XDoclet definition:
 * @struts.form name="y_addAFinfoForm"
 */
public class Y_addAFinfoForm extends ActionForm {
	/*
	 * Generated fields
	 */
	private Integer iid;
	/** zhongliang property */
	private Float zhongliang;

	/** fangliang property */
	private Float fangliang;

	/** end property */
	private Integer end;

	/** strat property */
	private Integer strat;

	/** pjtime property */
	private Integer pjtime;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the zhongliang.
	 * @return Float
	 */
	public Float getZhongliang() {
		return zhongliang;
	}

	/** 
	 * Set the zhongliang.
	 * @param zhongliang The zhongliang to set
	 */
	public void setZhongliang(Float zhongliang) {
		this.zhongliang = zhongliang;
	}

	/** 
	 * Returns the fangliang.
	 * @return Float
	 */
	public Float getFangliang() {
		return fangliang;
	}

	/** 
	 * Set the fangliang.
	 * @param fangliang The fangliang to set
	 */
	public void setFangliang(Float fangliang) {
		this.fangliang = fangliang;
	}

	/** 
	 * Returns the end.
	 * @return Integer
	 */
	public Integer getEnd() {
		return end;
	}

	/** 
	 * Set the end.
	 * @param end The end to set
	 */
	public void setEnd(Integer end) {
		this.end = end;
	}

	/** 
	 * Returns the strat.
	 * @return Integer
	 */
	public Integer getStrat() {
		return strat;
	}

	/** 
	 * Set the strat.
	 * @param strat The strat to set
	 */
	public void setStrat(Integer strat) {
		this.strat = strat;
	}

	/** 
	 * Returns the pjtime.
	 * @return Integer
	 */
	public Integer getPjtime() {
		return pjtime;
	}

	/** 
	 * Set the pjtime.
	 * @param pjtime The pjtime to set
	 */
	public void setPjtime(Integer pjtime) {
		this.pjtime = pjtime;
	}

	public Integer getIid() {
		return iid;
	}

	public void setIid(Integer iid) {
		this.iid = iid;
	}
}