/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yuntong.action.actionform;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-08-2007
 * 
 * XDoclet definition:
 * @struts.form name="y_findR1Form"
 */
public class Y_findR1Form extends ActionForm {
	/*
	 * Generated fields
	 */

	/** inputType property */
	private String inputType;

	/** inputID property */
	private String inputID;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the inputType.
	 * @return String
	 */
	public String getInputType() {
		return inputType;
	}

	/** 
	 * Set the inputType.
	 * @param inputType The inputType to set
	 */
	public void setInputType(String inputType) {
		this.inputType = inputType;
	}

	/** 
	 * Returns the inputID.
	 * @return String
	 */
	public String getInputID() {
		return inputID;
	}

	/** 
	 * Set the inputID.
	 * @param inputID The inputID to set
	 */
	public void setInputID(String inputID) {
		this.inputID = inputID;
	}
}