/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yuntong.action.actionform;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-11-2007
 * 
 * XDoclet definition:
 * @struts.form name="y_insertUserInfoForm"
 */
public class Y_insertUserInfoForm extends ValidatorForm {
	/*
	 * Generated fields
	 */

	/** userName property */
	private String userName;

	/** userCardId property */
	private String userCardId;

	/** userPwd2 property */
	private String userPwd2;

	/** userId property */
	private String userId;

	/** filiale property */
	private Integer filiale;

	/** userPhone property */
	private String userPhone;

	/** userTrueName property */
	private String userTrueName;

	/** userPwd1 property */
	private String userPwd1;

	/** userRole property */
	private Integer userRole;

	/** department property */
	private Integer department;
	
	private int userLoginNum;
	
	private String userLoginDate;
	
	private String userDate;

	/*
	 * Generated Methods
	 */

	public String getUserDate() {
		return userDate;
	}

	public void setUserDate(String userDate) {
		this.userDate = userDate;
	}

	public String getUserLoginDate() {
		return userLoginDate;
	}

	public void setUserLoginDate(String userLoginDate) {
		this.userLoginDate = userLoginDate;
	}

	public int getUserLoginNum() {
		return userLoginNum;
	}

	public void setUserLoginNum(int userLoginNum) {
		this.userLoginNum = userLoginNum;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the userName.
	 * @return String
	 */
	public String getUserName() {
		return userName;
	}

	/** 
	 * Set the userName.
	 * @param userName The userName to set
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/** 
	 * Returns the userCardId.
	 * @return String
	 */
	public String getUserCardId() {
		return userCardId;
	}

	/** 
	 * Set the userCardId.
	 * @param userCardId The userCardId to set
	 */
	public void setUserCardId(String userCardId) {
		this.userCardId = userCardId;
	}

	/** 
	 * Returns the userPwd2.
	 * @return String
	 */
	public String getUserPwd2() {
		return userPwd2;
	}

	/** 
	 * Set the userPwd2.
	 * @param userPwd2 The userPwd2 to set
	 */
	public void setUserPwd2(String userPwd2) {
		this.userPwd2 = userPwd2;
	}

	/** 
	 * Returns the userId.
	 * @return String
	 */
	public String getUserId() {
		return userId;
	}

	/** 
	 * Set the userId.
	 * @param userId The userId to set
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/** 
	 * Returns the filiale.
	 * @return Integer
	 */
	public Integer getFiliale() {
		return filiale;
	}

	/** 
	 * Set the filiale.
	 * @param filiale The filiale to set
	 */
	public void setFiliale(Integer filiale) {
		this.filiale = filiale;
	}

	/** 
	 * Returns the userPhone.
	 * @return String
	 */
	public String getUserPhone() {
		return userPhone;
	}

	/** 
	 * Set the userPhone.
	 * @param userPhone The userPhone to set
	 */
	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	/** 
	 * Returns the userTrueName.
	 * @return String
	 */
	public String getUserTrueName() {
		return userTrueName;
	}

	/** 
	 * Set the userTrueName.
	 * @param userTrueName The userTrueName to set
	 */
	public void setUserTrueName(String userTrueName) {
		this.userTrueName = userTrueName;
	}

	/** 
	 * Returns the userPwd1.
	 * @return String
	 */
	public String getUserPwd1() {
		return userPwd1;
	}

	/** 
	 * Set the userPwd1.
	 * @param userPwd1 The userPwd1 to set
	 */
	public void setUserPwd1(String userPwd1) {
		this.userPwd1 = userPwd1;
	}

	/** 
	 * Returns the userRole.
	 * @return Integer
	 */
	public Integer getUserRole() {
		return userRole;
	}

	/** 
	 * Set the userRole.
	 * @param userRole The userRole to set
	 */
	public void setUserRole(Integer userRole) {
		this.userRole = userRole;
	}

	/** 
	 * Returns the department.
	 * @return Integer
	 */
	public Integer getDepartment() {
		return department;
	}

	/** 
	 * Set the department.
	 * @param department The department to set
	 */
	public void setDepartment(Integer department) {
		this.department = department;
	}
}