/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yuntong.action.actionform;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-28-2007
 * 
 * XDoclet definition:
 * @struts.form name="y_LoginForm"
 */
public class Y_LoginForm extends ValidatorForm {
	/*
	 * Generated fields
	 */

	/** userName property */
	private String userName;

	/** userPwd property */
	private String userPwd;

	/** checkNum property */
	private String checkNum;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the userName.
	 * @return String
	 */
	public String getUserName() {
		return userName;
	}

	/** 
	 * Set the userName.
	 * @param userName The userName to set
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/** 
	 * Returns the userPwd.
	 * @return String
	 */
	public String getUserPwd() {
		return userPwd;
	}

	/** 
	 * Set the userPwd.
	 * @param userPwd The userPwd to set
	 */
	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd;
	}

	/** 
	 * Returns the checkNum.
	 * @return String
	 */
	public String getCheckNum() {
		return checkNum;
	}

	/** 
	 * Set the checkNum.
	 * @param checkNum The checkNum to set
	 */
	public void setCheckNum(String checkNum) {
		this.checkNum = checkNum;
	}
}