/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yuntong.action.actionform;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-01-2007
 * 
 * XDoclet definition:
 * @struts.form name="y_SHDJGoodsForm"
 */
public class Y_SHDJGoodsForm extends ValidatorForm {
	/*
	 * Generated fields
	 */

	/** paymentStyle property */
	private String paymentStyle;

	/** goodsHeft property */
	private String goodsHeft="0";

	/** goodsNumberUnit property */
	private String goodsNumberUnit;

	/** goodsValue property */
	private String goodsValue;

	/** goodsNumber property */
	private String goodsNumber;

	/** goodsBulk property */
	private String goodsBulk="0";

	/** goodsName property */
	private String goodsName;

	/** goodsRemark property */
	private String goodsRemark;

	/** freightStyle property */
	private String freightStyle;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the paymentStyle.
	 * @return String
	 */
	public String getPaymentStyle() {
		return paymentStyle;
	}

	/** 
	 * Set the paymentStyle.
	 * @param paymentStyle The paymentStyle to set
	 */
	public void setPaymentStyle(String paymentStyle) {
		this.paymentStyle = paymentStyle;
	}

	/** 
	 * Returns the goodsHeft.
	 * @return String
	 */
	public String getGoodsHeft() {
		return goodsHeft;
	}

	/** 
	 * Set the goodsHeft.
	 * @param goodsHeft The goodsHeft to set
	 */
	public void setGoodsHeft(String goodsHeft) {
		this.goodsHeft = goodsHeft;
	}

	/** 
	 * Returns the goodsNumberUnit.
	 * @return String
	 */
	public String getGoodsNumberUnit() {
		return goodsNumberUnit;
	}

	/** 
	 * Set the goodsNumberUnit.
	 * @param goodsNumberUnit The goodsNumberUnit to set
	 */
	public void setGoodsNumberUnit(String goodsNumberUnit) {
		this.goodsNumberUnit = goodsNumberUnit;
	}

	/** 
	 * Returns the goodsValue.
	 * @return String
	 */
	public String getGoodsValue() {
		return goodsValue;
	}

	/** 
	 * Set the goodsValue.
	 * @param goodsValue The goodsValue to set
	 */
	public void setGoodsValue(String goodsValue) {
		this.goodsValue = goodsValue;
	}

	/** 
	 * Returns the goodsNumber.
	 * @return String
	 */
	public String getGoodsNumber() {
		return goodsNumber;
	}

	/** 
	 * Set the goodsNumber.
	 * @param goodsNumber The goodsNumber to set
	 */
	public void setGoodsNumber(String goodsNumber) {
		this.goodsNumber = goodsNumber;
	}

	/** 
	 * Returns the goodsBulk.
	 * @return String
	 */
	public String getGoodsBulk() {
		return goodsBulk;
	}

	/** 
	 * Set the goodsBulk.
	 * @param goodsBulk The goodsBulk to set
	 */
	public void setGoodsBulk(String goodsBulk) {
		this.goodsBulk = goodsBulk;
	}

	/** 
	 * Returns the goodsName.
	 * @return String
	 */
	public String getGoodsName() {
		return goodsName;
	}

	/** 
	 * Set the goodsName.
	 * @param goodsName The goodsName to set
	 */
	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName;
	}

	/** 
	 * Returns the goodsRemark.
	 * @return String
	 */
	public String getGoodsRemark() {
		return goodsRemark;
	}

	/** 
	 * Set the goodsRemark.
	 * @param goodsRemark The goodsRemark to set
	 */
	public void setGoodsRemark(String goodsRemark) {
		this.goodsRemark = goodsRemark;
	}

	/** 
	 * Returns the freightStyle.
	 * @return String
	 */
	public String getFreightStyle() {
		return freightStyle;
	}

	/** 
	 * Set the freightStyle.
	 * @param freightStyle The freightStyle to set
	 */
	public void setFreightStyle(String freightStyle) {
		this.freightStyle = freightStyle;
	}
}