/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yuntong.action.actionform;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-26-2007
 * 
 * XDoclet definition:
 * @struts.form name="y_SHDJFactoryForm"
 */
public class Y_SHDJFactoryForm extends ValidatorForm {
	/*
	 * Generated fields
	 */

	/** factoryLinkman property */
	private String factoryLinkman;

	/** factoryEmail property */
	private String factoryEmail;

	/** factoryFax property */
	private String factoryFax;

	/** factoryID property */
	private String factoryID;

	/** factoryAddress property */
	private String factoryAddress;

	/** factoryName property */
	private String factoryName;

	/** factoryPostID property */
	private String factoryPostID;

	/** factoryInfo property */
	private String factoryInfo;

	/** factoryPhone property */
	private String factoryPhone;

	/** factoryArea property */
	private String factoryArea;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the factoryLinkman.
	 * @return String
	 */
	public String getFactoryLinkman() {
		return factoryLinkman;
	}

	/** 
	 * Set the factoryLinkman.
	 * @param factoryLinkman The factoryLinkman to set
	 */
	public void setFactoryLinkman(String factoryLinkman) {
		this.factoryLinkman = factoryLinkman;
	}

	/** 
	 * Returns the factoryEmail.
	 * @return String
	 */
	public String getFactoryEmail() {
		return factoryEmail;
	}

	/** 
	 * Set the factoryEmail.
	 * @param factoryEmail The factoryEmail to set
	 */
	public void setFactoryEmail(String factoryEmail) {
		this.factoryEmail = factoryEmail;
	}

	/** 
	 * Returns the factoryFax.
	 * @return String
	 */
	public String getFactoryFax() {
		return factoryFax;
	}

	/** 
	 * Set the factoryFax.
	 * @param factoryFax The factoryFax to set
	 */
	public void setFactoryFax(String factoryFax) {
		this.factoryFax = factoryFax;
	}

	/** 
	 * Returns the factoryID.
	 * @return String
	 */
	public String getFactoryID() {
		return factoryID;
	}

	/** 
	 * Set the factoryID.
	 * @param factoryID The factoryID to set
	 */
	public void setFactoryID(String factoryID) {
		this.factoryID = factoryID;
	}

	/** 
	 * Returns the factoryAddress.
	 * @return String
	 */
	public String getFactoryAddress() {
		return factoryAddress;
	}

	/** 
	 * Set the factoryAddress.
	 * @param factoryAddress The factoryAddress to set
	 */
	public void setFactoryAddress(String factoryAddress) {
		this.factoryAddress = factoryAddress;
	}

	/** 
	 * Returns the factoryName.
	 * @return String
	 */
	public String getFactoryName() {
		return factoryName;
	}

	/** 
	 * Set the factoryName.
	 * @param factoryName The factoryName to set
	 */
	public void setFactoryName(String factoryName) {
		this.factoryName = factoryName;
	}

	/** 
	 * Returns the factoryPostID.
	 * @return String
	 */
	public String getFactoryPostID() {
		return factoryPostID;
	}

	/** 
	 * Set the factoryPostID.
	 * @param factoryPostID The factoryPostID to set
	 */
	public void setFactoryPostID(String factoryPostID) {
		this.factoryPostID = factoryPostID;
	}

	/** 
	 * Returns the factoryInfo.
	 * @return String
	 */
	public String getFactoryInfo() {
		return factoryInfo;
	}

	/** 
	 * Set the factoryInfo.
	 * @param factoryInfo The factoryInfo to set
	 */
	public void setFactoryInfo(String factoryInfo) {
		this.factoryInfo = factoryInfo;
	}

	/** 
	 * Returns the factoryPhone.
	 * @return String
	 */
	public String getFactoryPhone() {
		return factoryPhone;
	}

	/** 
	 * Set the factoryPhone.
	 * @param factoryPhone The factoryPhone to set
	 */
	public void setFactoryPhone(String factoryPhone) {
		this.factoryPhone = factoryPhone;
	}

	/** 
	 * Returns the factoryArea.
	 * @return String
	 */
	public String getFactoryArea() {
		return factoryArea;
	}

	/** 
	 * Set the factoryArea.
	 * @param factoryArea The factoryArea to set
	 */
	public void setFactoryArea(String factoryArea) {
		this.factoryArea = factoryArea;
	}
}