/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yuntong.action.actionform;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-21-2007
 * 
 * XDoclet definition:
 * @struts.form name="y_UpdatePwdForm"
 */
public class Y_UpdatePwdForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** pwd1 property */
	private String pwd1;

	/** pwd3 property */
	private String pwd3;

	/** pwd2 property */
	private String pwd2;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the pwd1.
	 * @return String
	 */
	public String getPwd1() {
		return pwd1;
	}

	/** 
	 * Set the pwd1.
	 * @param pwd1 The pwd1 to set
	 */
	public void setPwd1(String pwd1) {
		this.pwd1 = pwd1;
	}

	/** 
	 * Returns the pwd3.
	 * @return String
	 */
	public String getPwd3() {
		return pwd3;
	}

	/** 
	 * Set the pwd3.
	 * @param pwd3 The pwd3 to set
	 */
	public void setPwd3(String pwd3) {
		this.pwd3 = pwd3;
	}

	/** 
	 * Returns the pwd2.
	 * @return String
	 */
	public String getPwd2() {
		return pwd2;
	}

	/** 
	 * Set the pwd2.
	 * @param pwd2 The pwd2 to set
	 */
	public void setPwd2(String pwd2) {
		this.pwd2 = pwd2;
	}
}