package com.yuntong.hibernate.database.po;

import java.util.Date;


/**
 * TAffiche generated by MyEclipse - Hibernate Tools
 */

public class TAffiche  implements java.io.Serializable {


    // Fields    

     private Integer afficheId;
     private TUserInfo TUserInfo;
     private String afficheTitle;
     private String afficheInfo;
     private Date afficheDateTime;


    // Constructors

    /** default constructor */
    public TAffiche() {
    }

	/** minimal constructor */
    public TAffiche(Integer afficheId) {
        this.afficheId = afficheId;
    }
    
    /** full constructor */
    public TAffiche(Integer afficheId, TUserInfo TUserInfo, String afficheTitle, String afficheInfo, Date afficheDateTime) {
        this.afficheId = afficheId;
        this.TUserInfo = TUserInfo;
        this.afficheTitle = afficheTitle;
        this.afficheInfo = afficheInfo;
        this.afficheDateTime = afficheDateTime;
    }

   
    // Property accessors

    public Integer getAfficheId() {
        return this.afficheId;
    }
    
    public void setAfficheId(Integer afficheId) {
        this.afficheId = afficheId;
    }

    public TUserInfo getTUserInfo() {
        return this.TUserInfo;
    }
    
    public void setTUserInfo(TUserInfo TUserInfo) {
        this.TUserInfo = TUserInfo;
    }

    public String getAfficheTitle() {
        return this.afficheTitle;
    }
    
    public void setAfficheTitle(String afficheTitle) {
        this.afficheTitle = afficheTitle;
    }

    public String getAfficheInfo() {
        return this.afficheInfo;
    }
    
    public void setAfficheInfo(String afficheInfo) {
        this.afficheInfo = afficheInfo;
    }

    public Date getAfficheDateTime() {
        return this.afficheDateTime;
    }
    
    public void setAfficheDateTime(Date afficheDateTime) {
        this.afficheDateTime = afficheDateTime;
    }
   








}