package com.yuntong.hibernate.database.po;

import java.util.HashSet;
import java.util.Set;


/**
 * TAgioType generated by MyEclipse - Hibernate Tools
 */

public class TAgioType  implements java.io.Serializable {


    // Fields    

     private Integer atypeId;
     private String atypeName;
     private String atypeInfo;
     private Set TAgioInfos = new HashSet(0);


    // Constructors

    /** default constructor */
    public TAgioType() {
    }

	/** minimal constructor */
    public TAgioType(Integer atypeId) {
        this.atypeId = atypeId;
    }
    
    /** full constructor */
    public TAgioType(Integer atypeId, String atypeName, String atypeInfo, Set TAgioInfos) {
        this.atypeId = atypeId;
        this.atypeName = atypeName;
        this.atypeInfo = atypeInfo;
        this.TAgioInfos = TAgioInfos;
    }

   
    // Property accessors

    public Integer getAtypeId() {
        return this.atypeId;
    }
    
    public void setAtypeId(Integer atypeId) {
        this.atypeId = atypeId;
    }

    public String getAtypeName() {
        return this.atypeName;
    }
    
    public void setAtypeName(String atypeName) {
        this.atypeName = atypeName;
    }

    public String getAtypeInfo() {
        return this.atypeInfo;
    }
    
    public void setAtypeInfo(String atypeInfo) {
        this.atypeInfo = atypeInfo;
    }

    public Set getTAgioInfos() {
        return this.TAgioInfos;
    }
    
    public void setTAgioInfos(Set TAgioInfos) {
        this.TAgioInfos = TAgioInfos;
    }
   








}