package com.yuntong.hibernate.database.po;



/**
 * TAreaFreightInfo generated by MyEclipse - Hibernate Tools
 */

public class TAreaFreightInfo  implements java.io.Serializable {


    // Fields    

     private Integer afrerghtId;
     private TAreaInfo TAreaInfoByAfrerghtEnd;
     private TAreaInfo TAreaInfoByAfrerghtBegin;
     private Integer afrerghtTime;
     private Float afrerghtHeft;
     private Float afrerghtBulk;


    // Constructors

    /** default constructor */
    public TAreaFreightInfo() {
    }

	/** minimal constructor */
    public TAreaFreightInfo(Integer afrerghtId, TAreaInfo TAreaInfoByAfrerghtEnd, TAreaInfo TAreaInfoByAfrerghtBegin) {
        this.afrerghtId = afrerghtId;
        this.TAreaInfoByAfrerghtEnd = TAreaInfoByAfrerghtEnd;
        this.TAreaInfoByAfrerghtBegin = TAreaInfoByAfrerghtBegin;
    }
    
    /** full constructor */
    public TAreaFreightInfo(Integer afrerghtId, TAreaInfo TAreaInfoByAfrerghtEnd, TAreaInfo TAreaInfoByAfrerghtBegin, Integer afrerghtTime, Float afrerghtHeft, Float afrerghtBulk) {
        this.afrerghtId = afrerghtId;
        this.TAreaInfoByAfrerghtEnd = TAreaInfoByAfrerghtEnd;
        this.TAreaInfoByAfrerghtBegin = TAreaInfoByAfrerghtBegin;
        this.afrerghtTime = afrerghtTime;
        this.afrerghtHeft = afrerghtHeft;
        this.afrerghtBulk = afrerghtBulk;
    }

   
    // Property accessors

    public Integer getAfrerghtId() {
        return this.afrerghtId;
    }
    
    public void setAfrerghtId(Integer afrerghtId) {
        this.afrerghtId = afrerghtId;
    }

    public TAreaInfo getTAreaInfoByAfrerghtEnd() {
        return this.TAreaInfoByAfrerghtEnd;
    }
    
    public void setTAreaInfoByAfrerghtEnd(TAreaInfo TAreaInfoByAfrerghtEnd) {
        this.TAreaInfoByAfrerghtEnd = TAreaInfoByAfrerghtEnd;
    }

    public TAreaInfo getTAreaInfoByAfrerghtBegin() {
        return this.TAreaInfoByAfrerghtBegin;
    }
    
    public void setTAreaInfoByAfrerghtBegin(TAreaInfo TAreaInfoByAfrerghtBegin) {
        this.TAreaInfoByAfrerghtBegin = TAreaInfoByAfrerghtBegin;
    }

    public Integer getAfrerghtTime() {
        return this.afrerghtTime;
    }
    
    public void setAfrerghtTime(Integer afrerghtTime) {
        this.afrerghtTime = afrerghtTime;
    }

    public Float getAfrerghtHeft() {
        return this.afrerghtHeft;
    }
    
    public void setAfrerghtHeft(Float afrerghtHeft) {
        this.afrerghtHeft = afrerghtHeft;
    }

    public Float getAfrerghtBulk() {
        return this.afrerghtBulk;
    }
    
    public void setAfrerghtBulk(Float afrerghtBulk) {
        this.afrerghtBulk = afrerghtBulk;
    }
   








}