package com.yuntong.hibernate.database.po;

import java.util.HashSet;
import java.util.Set;


/**
 * TCarType generated by MyEclipse - Hibernate Tools
 */

public class TCarType  implements java.io.Serializable {


    // Fields    

     private Integer carTypeId;
     private String carTypeName;
     private Set TRoadwaies = new HashSet(0);


    // Constructors

    /** default constructor */
    public TCarType() {
    }

	/** minimal constructor */
    public TCarType(Integer carTypeId) {
        this.carTypeId = carTypeId;
    }
    
    /** full constructor */
    public TCarType(Integer carTypeId, String carTypeName, Set TRoadwaies) {
        this.carTypeId = carTypeId;
        this.carTypeName = carTypeName;
        this.TRoadwaies = TRoadwaies;
    }

   
    // Property accessors

    public Integer getCarTypeId() {
        return this.carTypeId;
    }
    
    public void setCarTypeId(Integer carTypeId) {
        this.carTypeId = carTypeId;
    }

    public String getCarTypeName() {
        return this.carTypeName;
    }
    
    public void setCarTypeName(String carTypeName) {
        this.carTypeName = carTypeName;
    }

    public Set getTRoadwaies() {
        return this.TRoadwaies;
    }
    
    public void setTRoadwaies(Set TRoadwaies) {
        this.TRoadwaies = TRoadwaies;
    }
   








}