package com.yuntong.hibernate.database.po;



/**
 * TCue generated by MyEclipse - Hibernate Tools
 */

public class TCue  implements java.io.Serializable {


    // Fields    

     private Integer cueId;
     private String cuePlace;
     private String cueName;
     private String cueInfo;


    // Constructors

    /** default constructor */
    public TCue() {
    }

	/** minimal constructor */
    public TCue(Integer cueId) {
        this.cueId = cueId;
    }
    
    /** full constructor */
    public TCue(Integer cueId, String cuePlace, String cueName, String cueInfo) {
        this.cueId = cueId;
        this.cuePlace = cuePlace;
        this.cueName = cueName;
        this.cueInfo = cueInfo;
    }

   
    // Property accessors

    public Integer getCueId() {
        return this.cueId;
    }
    
    public void setCueId(Integer cueId) {
        this.cueId = cueId;
    }

    public String getCuePlace() {
        return this.cuePlace;
    }
    
    public void setCuePlace(String cuePlace) {
        this.cuePlace = cuePlace;
    }

    public String getCueName() {
        return this.cueName;
    }
    
    public void setCueName(String cueName) {
        this.cueName = cueName;
    }

    public String getCueInfo() {
        return this.cueInfo;
    }
    
    public void setCueInfo(String cueInfo) {
        this.cueInfo = cueInfo;
    }
   








}