package com.yuntong.hibernate.database.po;



/**
 * TDisrepareInfo generated by MyEclipse - Hibernate Tools
 */

public class TDisrepareInfo  implements java.io.Serializable {


    // Fields    

     private Integer disrepareGoodsId;
     private TRegisterInfo TRegisterInfo;
     private TRoadway TRoadway;
     private String disrepareCause;
     private Float disrepareMoney;
     private Float disrepareIndemnity;
     private String disrepareIndemnityMan;


    // Constructors

    /** default constructor */
    public TDisrepareInfo() {
    }

	/** minimal constructor */
    public TDisrepareInfo(Integer disrepareGoodsId, TRegisterInfo TRegisterInfo) {
        this.disrepareGoodsId = disrepareGoodsId;
        this.TRegisterInfo = TRegisterInfo;
    }
    
    /** full constructor */
    public TDisrepareInfo(Integer disrepareGoodsId, TRegisterInfo TRegisterInfo, TRoadway TRoadway, String disrepareCause, Float disrepareMoney, Float disrepareIndemnity, String disrepareIndemnityMan) {
        this.disrepareGoodsId = disrepareGoodsId;
        this.TRegisterInfo = TRegisterInfo;
        this.TRoadway = TRoadway;
        this.disrepareCause = disrepareCause;
        this.disrepareMoney = disrepareMoney;
        this.disrepareIndemnity = disrepareIndemnity;
        this.disrepareIndemnityMan = disrepareIndemnityMan;
    }

   
    // Property accessors

    public Integer getDisrepareGoodsId() {
        return this.disrepareGoodsId;
    }
    
    public void setDisrepareGoodsId(Integer disrepareGoodsId) {
        this.disrepareGoodsId = disrepareGoodsId;
    }

    public TRegisterInfo getTRegisterInfo() {
        return this.TRegisterInfo;
    }
    
    public void setTRegisterInfo(TRegisterInfo TRegisterInfo) {
        this.TRegisterInfo = TRegisterInfo;
    }

    public TRoadway getTRoadway() {
        return this.TRoadway;
    }
    
    public void setTRoadway(TRoadway TRoadway) {
        this.TRoadway = TRoadway;
    }

    public String getDisrepareCause() {
        return this.disrepareCause;
    }
    
    public void setDisrepareCause(String disrepareCause) {
        this.disrepareCause = disrepareCause;
    }

    public Float getDisrepareMoney() {
        return this.disrepareMoney;
    }
    
    public void setDisrepareMoney(Float disrepareMoney) {
        this.disrepareMoney = disrepareMoney;
    }

    public Float getDisrepareIndemnity() {
        return this.disrepareIndemnity;
    }
    
    public void setDisrepareIndemnity(Float disrepareIndemnity) {
        this.disrepareIndemnity = disrepareIndemnity;
    }

    public String getDisrepareIndemnityMan() {
        return this.disrepareIndemnityMan;
    }
    
    public void setDisrepareIndemnityMan(String disrepareIndemnityMan) {
        this.disrepareIndemnityMan = disrepareIndemnityMan;
    }
   








}