package com.yuntong.hibernate.database.po;



/**
 * TDrawInfo generated by MyEclipse - Hibernate Tools
 */

public class TDrawInfo  implements java.io.Serializable {


    // Fields    

     private Integer drawId;
     private TRegisterInfo TRegisterInfo;
     private TRoadway drawRoadwayId;
     

    // Constructors

    /** default constructor */
    public TDrawInfo() {
    	
    }

	/** minimal constructor */
    public TDrawInfo(Integer drawId) {
        this.drawId = drawId;
    }
    
    /** full constructor */
    public TDrawInfo(Integer drawId, TRegisterInfo TRegisterInfo, TRoadway drawRoadwayId) {
        this.drawId = drawId;
        this.TRegisterInfo = TRegisterInfo;
        this.drawRoadwayId = drawRoadwayId;
    }

   
    // Property accessors

    public Integer getDrawId() {
        return this.drawId;
    }
    
    public void setDrawId(Integer drawId) {
        this.drawId = drawId;
    }

    public TRegisterInfo getTRegisterInfo() {
        return this.TRegisterInfo;
    }
    
    public void setTRegisterInfo(TRegisterInfo TRegisterInfo) {
        this.TRegisterInfo = TRegisterInfo;
    }

	public TRoadway getDrawRoadwayId() {
		return drawRoadwayId;
	}

	public void setDrawRoadwayId(TRoadway drawRoadwayId) {
		this.drawRoadwayId = drawRoadwayId;
	}

    
   








}