package com.yuntong.hibernate.database.po;

import java.util.HashSet;
import java.util.Set;


/**
 * TDriverInfo generated by MyEclipse - Hibernate Tools
 */

public class TDriverInfo  implements java.io.Serializable {


    // Fields    

     private Integer driverId;
     private TFilialeInfo TFilialeInfo;
     private String driverName;
     private Integer driverAge;
     private Integer driverSex;
     private String driverPhoto;
     private String driverDriverCardId;
     private String driverCardId;
     private String driverPhoneNum;
     private String driverRemarkInfo;
     private Integer isLeisure;
     private Set TRoadwaies = new HashSet(0);


    // Constructors

    /** default constructor */
    public TDriverInfo() {
    }

	/** minimal constructor */
    public TDriverInfo(Integer driverId) {
        this.driverId = driverId;
    }
    
    /** full constructor */
    public TDriverInfo(Integer driverId, TFilialeInfo TFilialeInfo, String driverName, Integer driverAge, Integer driverSex, String driverPhoto, String driverDriverCardId, String driverCardId, String driverPhoneNum, String driverRemarkInfo, Set TRoadwaies) {
        this.driverId = driverId;
        this.TFilialeInfo = TFilialeInfo;
        this.driverName = driverName;
        this.driverAge = driverAge;
        this.driverSex = driverSex;
        this.driverPhoto = driverPhoto;
        this.driverDriverCardId = driverDriverCardId;
        this.driverCardId = driverCardId;
        this.driverPhoneNum = driverPhoneNum;
        this.driverRemarkInfo = driverRemarkInfo;
        this.TRoadwaies = TRoadwaies;
    }

   
    // Property accessors

    public Integer getDriverId() {
        return this.driverId;
    }
    
    public void setDriverId(Integer driverId) {
        this.driverId = driverId;
    }

    public TFilialeInfo getTFilialeInfo() {
        return this.TFilialeInfo;
    }
    
    public void setTFilialeInfo(TFilialeInfo TFilialeInfo) {
        this.TFilialeInfo = TFilialeInfo;
    }

    public String getDriverName() {
        return this.driverName;
    }
    
    public void setDriverName(String driverName) {
        this.driverName = driverName;
    }

    public Integer getDriverAge() {
        return this.driverAge;
    }
    
    public void setDriverAge(Integer driverAge) {
        this.driverAge = driverAge;
    }

    public Integer getDriverSex() {
        return this.driverSex;
    }
    
    public void setDriverSex(Integer driverSex) {
        this.driverSex = driverSex;
    }

    public String getDriverPhoto() {
        return this.driverPhoto;
    }
    
    public void setDriverPhoto(String driverPhoto) {
        this.driverPhoto = driverPhoto;
    }

    public String getDriverDriverCardId() {
        return this.driverDriverCardId;
    }
    
    public void setDriverDriverCardId(String driverDriverCardId) {
        this.driverDriverCardId = driverDriverCardId;
    }

    public String getDriverCardId() {
        return this.driverCardId;
    }
    
    public void setDriverCardId(String driverCardId) {
        this.driverCardId = driverCardId;
    }

    public String getDriverPhoneNum() {
        return this.driverPhoneNum;
    }
    
    public void setDriverPhoneNum(String driverPhoneNum) {
        this.driverPhoneNum = driverPhoneNum;
    }

    public String getDriverRemarkInfo() {
        return this.driverRemarkInfo;
    }
    
    public void setDriverRemarkInfo(String driverRemarkInfo) {
        this.driverRemarkInfo = driverRemarkInfo;
    }

    public Set getTRoadwaies() {
        return this.TRoadwaies;
    }
    
    public void setTRoadwaies(Set TRoadwaies) {
        this.TRoadwaies = TRoadwaies;
    }

	public Integer getIsLeisure() {
		return isLeisure;
	}

	public void setIsLeisure(Integer isLeisure) {
		this.isLeisure = isLeisure;
	}
   








}