package com.yuntong.hibernate.database.po;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * TFactoryInfo generated by MyEclipse - Hibernate Tools
 */

public class TFactoryInfo  implements java.io.Serializable {


    // Fields    

     private Integer factoryId;
     private TGrade TGrade;
     private TAreaInfo TAreaInfo;
     private String factoryName;
     private String factoryLinkman;
     private String factoryAddress;
     private String factoryPhone;
     private String factoryFax;
     private String factoryPostId;
     private String factoryEmail;
     private Float factoryConsumption;
     private String factoryRemark;
     private Date factoryDate;
     private Set TRegisterInfos = new HashSet(0);


    // Constructors

    /** default constructor */
    public TFactoryInfo() {
    }

	/** minimal constructor */
    public TFactoryInfo(Integer factoryId) {
        this.factoryId = factoryId;
    }
    
    /** full constructor */
    public TFactoryInfo(Integer factoryId, TGrade TGrade, TAreaInfo TAreaInfo, String factoryName, String factoryLinkman, String factoryAddress, String factoryPhone, String factoryFax, String factoryPostId, String factoryEmail, Float factoryConsumption, String factoryRemark, Date factoryDate, Set TRegisterInfos) {
        this.factoryId = factoryId;
        this.TGrade = TGrade;
        this.TAreaInfo = TAreaInfo;
        this.factoryName = factoryName;
        this.factoryLinkman = factoryLinkman;
        this.factoryAddress = factoryAddress;
        this.factoryPhone = factoryPhone;
        this.factoryFax = factoryFax;
        this.factoryPostId = factoryPostId;
        this.factoryEmail = factoryEmail;
        this.factoryConsumption = factoryConsumption;
        this.factoryRemark = factoryRemark;
        this.factoryDate = factoryDate;
        this.TRegisterInfos = TRegisterInfos;
    }

   
    // Property accessors

    public Integer getFactoryId() {
        return this.factoryId;
    }
    
    public void setFactoryId(Integer factoryId) {
        this.factoryId = factoryId;
    }

    public TGrade getTGrade() {
        return this.TGrade;
    }
    
    public void setTGrade(TGrade TGrade) {
        this.TGrade = TGrade;
    }

    public TAreaInfo getTAreaInfo() {
        return this.TAreaInfo;
    }
    
    public void setTAreaInfo(TAreaInfo TAreaInfo) {
        this.TAreaInfo = TAreaInfo;
    }

    public String getFactoryName() {
        return this.factoryName;
    }
    
    public void setFactoryName(String factoryName) {
        this.factoryName = factoryName;
    }

    public String getFactoryLinkman() {
        return this.factoryLinkman;
    }
    
    public void setFactoryLinkman(String factoryLinkman) {
        this.factoryLinkman = factoryLinkman;
    }

    public String getFactoryAddress() {
        return this.factoryAddress;
    }
    
    public void setFactoryAddress(String factoryAddress) {
        this.factoryAddress = factoryAddress;
    }

    public String getFactoryPhone() {
        return this.factoryPhone;
    }
    
    public void setFactoryPhone(String factoryPhone) {
        this.factoryPhone = factoryPhone;
    }

    public String getFactoryFax() {
        return this.factoryFax;
    }
    
    public void setFactoryFax(String factoryFax) {
        this.factoryFax = factoryFax;
    }

    public String getFactoryPostId() {
        return this.factoryPostId;
    }
    
    public void setFactoryPostId(String factoryPostId) {
        this.factoryPostId = factoryPostId;
    }

    public String getFactoryEmail() {
        return this.factoryEmail;
    }
    
    public void setFactoryEmail(String factoryEmail) {
        this.factoryEmail = factoryEmail;
    }

    public Float getFactoryConsumption() {
        return this.factoryConsumption;
    }
    
    public void setFactoryConsumption(Float factoryConsumption) {
        this.factoryConsumption = factoryConsumption;
    }

    public String getFactoryRemark() {
        return this.factoryRemark;
    }
    
    public void setFactoryRemark(String factoryRemark) {
        this.factoryRemark = factoryRemark;
    }

    public Date getFactoryDate() {
        return this.factoryDate;
    }
    
    public void setFactoryDate(Date factoryDate) {
        this.factoryDate = factoryDate;
    }

    public Set getTRegisterInfos() {
        return this.TRegisterInfos;
    }
    
    public void setTRegisterInfos(Set TRegisterInfos) {
        this.TRegisterInfos = TRegisterInfos;
    }
   








}