package com.yuntong.hibernate.database.po;

import java.util.HashSet;
import java.util.List;
import java.util.Set;


/**
 * TFilialeInfo generated by MyEclipse - Hibernate Tools
 */

public class TFilialeInfo  implements java.io.Serializable {


    // Fields    

     private Integer filialeId;
     private TAreaInfo TAreaInfo;
     private String filialeName;
     private String filialeLinkman;
     private String filialePhone;
     private String filialeAddress;
     private String filialeEmail;
     private Set TTruckInfos = new HashSet(0);
     private Set TUserInfos = new HashSet(0);
     private Set TDriverInfos = new HashSet(0);


    // Constructors

    /** default constructor */
    public TFilialeInfo() {
    }
   
    
	/** minimal constructor */
    public TFilialeInfo(Integer filialeId) {
        this.filialeId = filialeId;
    }
    
    /** full constructor */
    public TFilialeInfo(Integer filialeId, TAreaInfo TAreaInfo, String filialeName, String filialeLinkman, String filialePhone, String filialeAddress, String filialeEmail, Set TTruckInfos, Set TUserInfos, Set TDriverInfos) {
        this.filialeId = filialeId;
        this.TAreaInfo = TAreaInfo;
        this.filialeName = filialeName;
        this.filialeLinkman = filialeLinkman;
        this.filialePhone = filialePhone;
        this.filialeAddress = filialeAddress;
        this.filialeEmail = filialeEmail;
        this.TTruckInfos = TTruckInfos;
        this.TUserInfos = TUserInfos;
        this.TDriverInfos = TDriverInfos;
    }

   
    // Property accessors

    public Integer getFilialeId() {
        return this.filialeId;
    }
    
    public void setFilialeId(Integer filialeId) {
        this.filialeId = filialeId;
    }

    public TAreaInfo getTAreaInfo() {
        return this.TAreaInfo;
    }
    
    public void setTAreaInfo(TAreaInfo TAreaInfo) {
        this.TAreaInfo = TAreaInfo;
    }

    public String getFilialeName() {
        return this.filialeName;
    }
    
    public void setFilialeName(String filialeName) {
        this.filialeName = filialeName;
    }

    public String getFilialeLinkman() {
        return this.filialeLinkman;
    }
    
    public void setFilialeLinkman(String filialeLinkman) {
        this.filialeLinkman = filialeLinkman;
    }

    public String getFilialePhone() {
        return this.filialePhone;
    }
    
    public void setFilialePhone(String filialePhone) {
        this.filialePhone = filialePhone;
    }

    public String getFilialeAddress() {
        return this.filialeAddress;
    }
    
    public void setFilialeAddress(String filialeAddress) {
        this.filialeAddress = filialeAddress;
    }

    public String getFilialeEmail() {
        return this.filialeEmail;
    }
    
    public void setFilialeEmail(String filialeEmail) {
        this.filialeEmail = filialeEmail;
    }

    public Set getTTruckInfos() {
        return this.TTruckInfos;
    }
    
    public void setTTruckInfos(Set TTruckInfos) {
        this.TTruckInfos = TTruckInfos;
    }

    public Set getTUserInfos() {
        return this.TUserInfos;
    }
    
    public void setTUserInfos(Set TUserInfos) {
        this.TUserInfos = TUserInfos;
    }

    public Set getTDriverInfos() {
        return this.TDriverInfos;
    }
    
    public void setTDriverInfos(Set TDriverInfos) {
        this.TDriverInfos = TDriverInfos;
    }
   








}