package com.yuntong.hibernate.database.po;

import java.util.HashSet;
import java.util.Set;


/**
 * TFreightStyle generated by MyEclipse - Hibernate Tools
 */

public class TFreightStyle  implements java.io.Serializable {


    // Fields    

     private Integer freightId;
     private String freightName;
     private String freightRemark;
     private Set TRegisterInfos = new HashSet(0);


    // Constructors

    /** default constructor */
    public TFreightStyle() {
    }

	/** minimal constructor */
    public TFreightStyle(Integer freightId) {
        this.freightId = freightId;
    }
    
    /** full constructor */
    public TFreightStyle(Integer freightId, String freightName, String freightRemark, Set TRegisterInfos) {
        this.freightId = freightId;
        this.freightName = freightName;
        this.freightRemark = freightRemark;
        this.TRegisterInfos = TRegisterInfos;
    }

   
    // Property accessors

    public Integer getFreightId() {
        return this.freightId;
    }
    
    public void setFreightId(Integer freightId) {
        this.freightId = freightId;
    }

    public String getFreightName() {
        return this.freightName;
    }
    
    public void setFreightName(String freightName) {
        this.freightName = freightName;
    }

    public String getFreightRemark() {
        return this.freightRemark;
    }
    
    public void setFreightRemark(String freightRemark) {
        this.freightRemark = freightRemark;
    }

    public Set getTRegisterInfos() {
        return this.TRegisterInfos;
    }
    
    public void setTRegisterInfos(Set TRegisterInfos) {
        this.TRegisterInfos = TRegisterInfos;
    }
   








}