package com.yuntong.hibernate.database.po;



/**
 * TMarketInfoId generated by MyEclipse - Hibernate Tools
 */

public class TMarketInfoId  implements java.io.Serializable {


    // Fields    

     private TAreaInfo TAreaInfo;
     private Integer marketId;


    // Constructors

    /** default constructor */
    public TMarketInfoId() {
    }

    
    /** full constructor */
    public TMarketInfoId(TAreaInfo TAreaInfo, Integer marketId) {
        this.TAreaInfo = TAreaInfo;
        this.marketId = marketId;
    }

   
    // Property accessors

    public TAreaInfo getTAreaInfo() {
        return this.TAreaInfo;
    }
    
    public void setTAreaInfo(TAreaInfo TAreaInfo) {
        this.TAreaInfo = TAreaInfo;
    }

    public Integer getMarketId() {
        return this.marketId;
    }
    
    public void setMarketId(Integer marketId) {
        this.marketId = marketId;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TMarketInfoId) ) return false;
		 TMarketInfoId castOther = ( TMarketInfoId ) other; 
         
		 return ( (this.getTAreaInfo()==castOther.getTAreaInfo()) || ( this.getTAreaInfo()!=null && castOther.getTAreaInfo()!=null && this.getTAreaInfo().equals(castOther.getTAreaInfo()) ) )
 && ( (this.getMarketId()==castOther.getMarketId()) || ( this.getMarketId()!=null && castOther.getMarketId()!=null && this.getMarketId().equals(castOther.getMarketId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTAreaInfo() == null ? 0 : this.getTAreaInfo().hashCode() );
         result = 37 * result + ( getMarketId() == null ? 0 : this.getMarketId().hashCode() );
         return result;
   }   





}