package com.yuntong.hibernate.database.po;

import java.util.HashSet;
import java.util.Set;


/**
 * TMarketInfo generated by MyEclipse - Hibernate Tools
 */

public class TMarketInfo  implements java.io.Serializable {


    // Fields    

     private Integer marketId;
     private TAreaInfo TAreaInfo;
     private String marketName;
     private String marketAddress;
     private String markeyPostId;
     private Set TClientInfos = new HashSet(0);


    // Constructors

    /** default constructor */
    public TMarketInfo() {
    }

	/** minimal constructor */
    public TMarketInfo(Integer marketId, TAreaInfo TAreaInfo) {
        this.marketId = marketId;
        this.TAreaInfo = TAreaInfo;
    }
    
    /** full constructor */
    public TMarketInfo(Integer marketId, TAreaInfo TAreaInfo, String marketName, String marketAddress, String markeyPostId, Set TClientInfos) {
        this.marketId = marketId;
        this.TAreaInfo = TAreaInfo;
        this.marketName = marketName;
        this.marketAddress = marketAddress;
        this.markeyPostId = markeyPostId;
        this.TClientInfos = TClientInfos;
    }

   
    // Property accessors

    public Integer getMarketId() {
        return this.marketId;
    }
    
    public void setMarketId(Integer marketId) {
        this.marketId = marketId;
    }

    public TAreaInfo getTAreaInfo() {
        return this.TAreaInfo;
    }
    
    public void setTAreaInfo(TAreaInfo TAreaInfo) {
        this.TAreaInfo = TAreaInfo;
    }

    public String getMarketName() {
        return this.marketName;
    }
    
    public void setMarketName(String marketName) {
        this.marketName = marketName;
    }

    public String getMarketAddress() {
        return this.marketAddress;
    }
    
    public void setMarketAddress(String marketAddress) {
        this.marketAddress = marketAddress;
    }

    public String getMarkeyPostId() {
        return this.markeyPostId;
    }
    
    public void setMarkeyPostId(String markeyPostId) {
        this.markeyPostId = markeyPostId;
    }

    public Set getTClientInfos() {
        return this.TClientInfos;
    }
    
    public void setTClientInfos(Set TClientInfos) {
        this.TClientInfos = TClientInfos;
    }
   








}