package com.yuntong.hibernate.database.po;

import java.util.HashSet;
import java.util.Set;


/**
 * TPaymentOfGoodsStyle generated by MyEclipse - Hibernate Tools
 */

public class TPaymentOfGoodsStyle  implements java.io.Serializable {


    // Fields    

     private Integer paymentId;
     private String paymentName;
     private String paymentRemark;
     private Set TGoodsInfos = new HashSet(0);


    // Constructors

    /** default constructor */
    public TPaymentOfGoodsStyle() {
    }

	/** minimal constructor */
    public TPaymentOfGoodsStyle(Integer paymentId) {
        this.paymentId = paymentId;
    }
    
    /** full constructor */
    public TPaymentOfGoodsStyle(Integer paymentId, String paymentName, String paymentRemark, Set TGoodsInfos) {
        this.paymentId = paymentId;
        this.paymentName = paymentName;
        this.paymentRemark = paymentRemark;
        this.TGoodsInfos = TGoodsInfos;
    }

   
    // Property accessors

    public Integer getPaymentId() {
        return this.paymentId;
    }
    
    public void setPaymentId(Integer paymentId) {
        this.paymentId = paymentId;
    }

    public String getPaymentName() {
        return this.paymentName;
    }
    
    public void setPaymentName(String paymentName) {
        this.paymentName = paymentName;
    }

    public String getPaymentRemark() {
        return this.paymentRemark;
    }
    
    public void setPaymentRemark(String paymentRemark) {
        this.paymentRemark = paymentRemark;
    }

    public Set getTGoodsInfos() {
        return this.TGoodsInfos;
    }
    
    public void setTGoodsInfos(Set TGoodsInfos) {
        this.TGoodsInfos = TGoodsInfos;
    }
   








}