package com.yuntong.hibernate.database.po;

import java.util.HashSet;
import java.util.Set;


/**
 * TRegisterState generated by MyEclipse - Hibernate Tools
 */

public class TRegisterState  implements java.io.Serializable {


    // Fields    

     private Integer rstateId;
     private String rstateName;
     private String rstateRemark;
     private Set TRegisterInfos = new HashSet(0);


    // Constructors

    /** default constructor */
    public TRegisterState() {
    }

	/** minimal constructor */
    public TRegisterState(Integer rstateId) {
        this.rstateId = rstateId;
    }
    
    /** full constructor */
    public TRegisterState(Integer rstateId, String rstateName, String rstateRemark, Set TRegisterInfos) {
        this.rstateId = rstateId;
        this.rstateName = rstateName;
        this.rstateRemark = rstateRemark;
        this.TRegisterInfos = TRegisterInfos;
    }

   
    // Property accessors

    public Integer getRstateId() {
        return this.rstateId;
    }
    
    public void setRstateId(Integer rstateId) {
        this.rstateId = rstateId;
    }

    public String getRstateName() {
        return this.rstateName;
    }
    
    public void setRstateName(String rstateName) {
        this.rstateName = rstateName;
    }

    public String getRstateRemark() {
        return this.rstateRemark;
    }
    
    public void setRstateRemark(String rstateRemark) {
        this.rstateRemark = rstateRemark;
    }

    public Set getTRegisterInfos() {
        return this.TRegisterInfos;
    }
    
    public void setTRegisterInfos(Set TRegisterInfos) {
        this.TRegisterInfos = TRegisterInfos;
    }
   








}