package com.yuntong.hibernate.database.po;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * TRoadway generated by MyEclipse - Hibernate Tools
 */

public class TRoadway  implements java.io.Serializable {


    // Fields    

     private Integer roadwayId;
     private TTruckInfo TTruckInfo;
     private TCarType TCarType;
     private TDriverInfo TDriverInfo;
     private Date roadStartDate;
     private Date roadArrive;
     private Set TTrafficLogs = new HashSet(0);
     private Set TDrawInfos =new HashSet(0);
     private Set TDisrepareInfos = new HashSet(0);


    // Constructors

    /** default constructor */
    public TRoadway() {
    }

	/** minimal constructor */
    public TRoadway(Integer roadwayId) {
        this.roadwayId = roadwayId;
    }
    
    /** full constructor */
    public TRoadway(Integer roadwayId, TTruckInfo TTruckInfo, TCarType TCarType, TDriverInfo TDriverInfo, Date roadStartDate, Date roadArrive, Set TTrafficLogs, Set TDisrepareInfos,Set TDrawInfos) {
        this.roadwayId = roadwayId;
        this.TTruckInfo = TTruckInfo;
        this.TCarType = TCarType;
        this.TDriverInfo = TDriverInfo;
        this.roadStartDate = roadStartDate;
        this.roadArrive = roadArrive;
        this.TTrafficLogs = TTrafficLogs;
        this.TDisrepareInfos = TDisrepareInfos;
        this.TDrawInfos=TDrawInfos;
    }

   
    // Property accessors

    public Integer getRoadwayId() {
        return this.roadwayId;
    }
    
    public void setRoadwayId(Integer roadwayId) {
        this.roadwayId = roadwayId;
    }

    public TTruckInfo getTTruckInfo() {
        return this.TTruckInfo;
    }
    
    public void setTTruckInfo(TTruckInfo TTruckInfo) {
        this.TTruckInfo = TTruckInfo;
    }

    public TCarType getTCarType() {
        return this.TCarType;
    }
    
    public void setTCarType(TCarType TCarType) {
        this.TCarType = TCarType;
    }

    public TDriverInfo getTDriverInfo() {
        return this.TDriverInfo;
    }
    
    public void setTDriverInfo(TDriverInfo TDriverInfo) {
        this.TDriverInfo = TDriverInfo;
    }

    public Date getRoadStartDate() {
        return this.roadStartDate;
    }
    
    public void setRoadStartDate(Date roadStartDate) {
        this.roadStartDate = roadStartDate;
    }

    public Date getRoadArrive() {
        return this.roadArrive;
    }
    
    public void setRoadArrive(Date roadArrive) {
        this.roadArrive = roadArrive;
    }

    public Set getTTrafficLogs() {
        return this.TTrafficLogs;
    }
    
    public void setTTrafficLogs(Set TTrafficLogs) {
        this.TTrafficLogs = TTrafficLogs;
    }

    public Set getTDisrepareInfos() {
        return this.TDisrepareInfos;
    }
    
    public void setTDisrepareInfos(Set TDisrepareInfos) {
        this.TDisrepareInfos = TDisrepareInfos;
    }

	public Set getTDrawInfos() {
		return TDrawInfos;
	}

	public void setTDrawInfos(Set drawInfos) {
		TDrawInfos = drawInfos;
	}
   








}