package com.yuntong.hibernate.database.po;



/**
 * TTrafficLog generated by MyEclipse - Hibernate Tools
 */

public class TTrafficLog  implements java.io.Serializable {


    // Fields    

     private Integer logId;
     private TRoadway TRoadway;
     private TRegisterInfo TRegisterInfo;


    // Constructors

    /** default constructor */
    public TTrafficLog() {
    }

	/** minimal constructor */
    public TTrafficLog(Integer logId) {
        this.logId = logId;
    }
    
    /** full constructor */
    public TTrafficLog(Integer logId, TRoadway TRoadway, TRegisterInfo TRegisterInfo) {
        this.logId = logId;
        this.TRoadway = TRoadway;
        this.TRegisterInfo = TRegisterInfo;
    }

   
    // Property accessors

    public Integer getLogId() {
        return this.logId;
    }
    
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    public TRoadway getTRoadway() {
        return this.TRoadway;
    }
    
    public void setTRoadway(TRoadway TRoadway) {
        this.TRoadway = TRoadway;
    }

    public TRegisterInfo getTRegisterInfo() {
        return this.TRegisterInfo;
    }
    
    public void setTRegisterInfo(TRegisterInfo TRegisterInfo) {
        this.TRegisterInfo = TRegisterInfo;
    }
   








}