package com.yuntong.hibernate.database.po;

import java.util.HashSet;
import java.util.Set;


/**
 * TTruckStyle generated by MyEclipse - Hibernate Tools
 */

public class TTruckStyle  implements java.io.Serializable {


    // Fields    

     private Integer truckStyleId;
     private String truckStyleName;
     private Long truckStyleTonnage;
     private Long truckStyleCubage;
     private Set TTruckInfos = new HashSet(0);


    // Constructors

    /** default constructor */
    public TTruckStyle() {
    }

	/** minimal constructor */
    public TTruckStyle(Integer truckStyleId) {
        this.truckStyleId = truckStyleId;
    }
    
    /** full constructor */
    public TTruckStyle(Integer truckStyleId, String truckStyleName, Long truckStyleTonnage, Long truckStyleCubage, Set TTruckInfos) {
        this.truckStyleId = truckStyleId;
        this.truckStyleName = truckStyleName;
        this.truckStyleTonnage = truckStyleTonnage;
        this.truckStyleCubage = truckStyleCubage;
        this.TTruckInfos = TTruckInfos;
    }

   
    // Property accessors

    public Integer getTruckStyleId() {
        return this.truckStyleId;
    }
    
    public void setTruckStyleId(Integer truckStyleId) {
        this.truckStyleId = truckStyleId;
    }

    public String getTruckStyleName() {
        return this.truckStyleName;
    }
    
    public void setTruckStyleName(String truckStyleName) {
        this.truckStyleName = truckStyleName;
    }

    public Long getTruckStyleTonnage() {
        return this.truckStyleTonnage;
    }
    
    public void setTruckStyleTonnage(Long truckStyleTonnage) {
        this.truckStyleTonnage = truckStyleTonnage;
    }

    public Long getTruckStyleCubage() {
        return this.truckStyleCubage;
    }
    
    public void setTruckStyleCubage(Long truckStyleCubage) {
        this.truckStyleCubage = truckStyleCubage;
    }

    public Set getTTruckInfos() {
        return this.TTruckInfos;
    }
    
    public void setTTruckInfos(Set TTruckInfos) {
        this.TTruckInfos = TTruckInfos;
    }
   








}