package com.yuntong.hibernate.database.po;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * TTruckInfo generated by MyEclipse - Hibernate Tools
 */

public class TTruckInfo  implements java.io.Serializable {


    // Fields    

     private Integer truckId;
     private TFilialeInfo TFilialeInfo;
     private TTruckStyle TTruckStyle;
     private String truckNum;
     private String truckEngineNum;
     private String truckRunNum;
     private String truckInsuranceNum;
     private String truckColor;
     private String truckPhoto;
     private String truckBuyDate;
     private Integer truckFixed;
     private Integer isLeisure;
     private Set TRoadwaies = new HashSet(0);


    // Constructors

    /** default constructor */
    public TTruckInfo() {
    }

	/** minimal constructor */
    public TTruckInfo(Integer truckId) {
        this.truckId = truckId;
    }
    
    /** full constructor */
    public TTruckInfo(Integer truckId, TFilialeInfo TFilialeInfo, TTruckStyle TTruckStyle, String truckNum, String truckEngineNum, String truckRunNum, String truckInsuranceNum, String truckColor, String truckPhoto, String truckBuyDate, Integer truckFixed, Set TRoadwaies) {
        this.truckId = truckId;
        this.TFilialeInfo = TFilialeInfo;
        this.TTruckStyle = TTruckStyle;
        this.truckNum = truckNum;
        this.truckEngineNum = truckEngineNum;
        this.truckRunNum = truckRunNum;
        this.truckInsuranceNum = truckInsuranceNum;
        this.truckColor = truckColor;
        this.truckPhoto = truckPhoto;
        this.truckBuyDate = truckBuyDate;
        this.truckFixed = truckFixed;
        this.TRoadwaies = TRoadwaies;
    }

   
    // Property accessors

    public Integer getTruckId() {
        return this.truckId;
    }
    
    public void setTruckId(Integer truckId) {
        this.truckId = truckId;
    }

    public TFilialeInfo getTFilialeInfo() {
        return this.TFilialeInfo;
    }
    
    public void setTFilialeInfo(TFilialeInfo TFilialeInfo) {
        this.TFilialeInfo = TFilialeInfo;
    }

    public TTruckStyle getTTruckStyle() {
        return this.TTruckStyle;
    }
    
    public void setTTruckStyle(TTruckStyle TTruckStyle) {
        this.TTruckStyle = TTruckStyle;
    }

    public String getTruckNum() {
        return this.truckNum;
    }
    
    public void setTruckNum(String truckNum) {
        this.truckNum = truckNum;
    }

    public String getTruckEngineNum() {
        return this.truckEngineNum;
    }
    
    public void setTruckEngineNum(String truckEngineNum) {
        this.truckEngineNum = truckEngineNum;
    }

    public String getTruckRunNum() {
        return this.truckRunNum;
    }
    
    public void setTruckRunNum(String truckRunNum) {
        this.truckRunNum = truckRunNum;
    }

    public String getTruckInsuranceNum() {
        return this.truckInsuranceNum;
    }
    
    public void setTruckInsuranceNum(String truckInsuranceNum) {
        this.truckInsuranceNum = truckInsuranceNum;
    }

    public String getTruckColor() {
        return this.truckColor;
    }
    
    public void setTruckColor(String truckColor) {
        this.truckColor = truckColor;
    }

    public String getTruckPhoto() {
        return this.truckPhoto;
    }
    
    public void setTruckPhoto(String truckPhoto) {
        this.truckPhoto = truckPhoto;
    }

   
    public String getTruckBuyDate() {
		return truckBuyDate;
	}

	public void setTruckBuyDate(String truckBuyDate) {
		this.truckBuyDate = truckBuyDate;
	}

	public Integer getTruckFixed() {
        return this.truckFixed;
    }
    
    public void setTruckFixed(Integer truckFixed) {
        this.truckFixed = truckFixed;
    }

    public Set getTRoadwaies() {
        return this.TRoadwaies;
    }
    
    public void setTRoadwaies(Set TRoadwaies) {
        this.TRoadwaies = TRoadwaies;
    }

	public Integer getIsLeisure() {
		return isLeisure;
	}

	public void setIsLeisure(Integer isLeisure) {
		this.isLeisure = isLeisure;
	}
   








}