package com.yuntong.hibernate.database.po;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * TUserInfo generated by MyEclipse - Hibernate Tools
 */

public class TUserInfo  implements java.io.Serializable {


    // Fields    

     private Integer userId;
     private TDepartment TDepartment;
     private TFilialeInfo TFilialeInfo;
     private TRoleInfo TRoleInfo;
     private String userUseName;
     private String userName;
     private String userPassword;
     private String userPhone;
     private String userCardId;
     private Integer userLoginNum;
     private Date userLoginDate;
     private Date userDate;
     private Set TRegisterInfos = new HashSet(0);
     private Set TAffiches = new HashSet(0);


    // Constructors

    /** default constructor */
    public TUserInfo() {
    }

	/** minimal constructor */
    public TUserInfo(Integer userId) {
        this.userId = userId;
    }
    
    /** full constructor */
    public TUserInfo(Integer userId, TDepartment TDepartment, TFilialeInfo TFilialeInfo, TRoleInfo TRoleInfo, String userUseName, String userName, String userPassword, String userPhone, String userCardId, Integer userLoginNum, Date userLoginDate, Date userDate, Set TRegisterInfos, Set TAffiches) {
        this.userId = userId;
        this.TDepartment = TDepartment;
        this.TFilialeInfo = TFilialeInfo;
        this.TRoleInfo = TRoleInfo;
        this.userUseName = userUseName;
        this.userName = userName;
        this.userPassword = userPassword;
        this.userPhone = userPhone;
        this.userCardId = userCardId;
        this.userLoginNum = userLoginNum;
        this.userLoginDate = userLoginDate;
        this.userDate = userDate;
        this.TRegisterInfos = TRegisterInfos;
        this.TAffiches = TAffiches;
    }

   
    // Property accessors

    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public TDepartment getTDepartment() {
        return this.TDepartment;
    }
    
    public void setTDepartment(TDepartment TDepartment) {
        this.TDepartment = TDepartment;
    }

    public TFilialeInfo getTFilialeInfo() {
        return this.TFilialeInfo;
    }
    
    public void setTFilialeInfo(TFilialeInfo TFilialeInfo) {
        this.TFilialeInfo = TFilialeInfo;
    }

    public TRoleInfo getTRoleInfo() {
        return this.TRoleInfo;
    }
    
    public void setTRoleInfo(TRoleInfo TRoleInfo) {
        this.TRoleInfo = TRoleInfo;
    }

    public String getUserUseName() {
        return this.userUseName;
    }
    
    public void setUserUseName(String userUseName) {
        this.userUseName = userUseName;
    }

    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    public String getUserPhone() {
        return this.userPhone;
    }
    
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }

    public String getUserCardId() {
        return this.userCardId;
    }
    
    public void setUserCardId(String userCardId) {
        this.userCardId = userCardId;
    }

    public Integer getUserLoginNum() {
        return this.userLoginNum;
    }
    
    public void setUserLoginNum(Integer userLoginNum) {
        this.userLoginNum = userLoginNum;
    }

    public Date getUserLoginDate() {
        return this.userLoginDate;
    }
    
    public void setUserLoginDate(Date userLoginDate) {
        this.userLoginDate = userLoginDate;
    }

    public Date getUserDate() {
        return this.userDate;
    }
    
    public void setUserDate(Date userDate) {
        this.userDate = userDate;
    }

    public Set getTRegisterInfos() {
        return this.TRegisterInfos;
    }
    
    public void setTRegisterInfos(Set TRegisterInfos) {
        this.TRegisterInfos = TRegisterInfos;
    }

    public Set getTAffiches() {
        return this.TAffiches;
    }
    
    public void setTAffiches(Set TAffiches) {
        this.TAffiches = TAffiches;
    }
   








}